#ifndef VICTIM_CACHE_H
#define VICTIM_CACHE_H

#include <iostream>
#include <algorithm>
#include <array>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <unordered_map>
#include <deque>

#include "champsim.h"


class IndexHash
{
  public:
    
    virtual ~IndexHash() = default;
    
    virtual uint32_t get_set(uint64_t address) = 0; 

};

class DefaultHash : public IndexHash
{
  public:
    DefaultHash(uint32_t _num_set, uint32_t _num_way, uint32_t _offset_bits) : num_set(_num_set), num_way(_num_way), offset_bits(_offset_bits) {}
    
    virtual ~DefaultHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      return (address >> offset_bits) & champsim::bitmask(champsim::lg2(num_set));
    }

  private:
    uint32_t num_set, num_way, offset_bits;
};


class ModuloHash : public IndexHash 
{
  public:
    ModuloHash(uint32_t _num_set, uint32_t _num_way, uint32_t _offset_bits) : num_set(_num_set), num_way(_num_way), offset_bits(_offset_bits) {}
    
    virtual ~ModuloHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      return (address >> offset_bits) & champsim::bitmask(champsim::lg2(num_set));
    }

  private:
    uint32_t num_set, num_way, offset_bits;
};

class XORHash : public IndexHash
{
  public:
    XORHash(uint32_t _num_set, uint32_t _num_way) : num_set(_num_set), num_way(_num_way) {}
    
    virtual ~XORHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      uint64_t block = address >> 6;
      uint32_t set_idx = (block ^ (block >> 7) ^ (block >> 13)) & (num_set - 1); 
      // we can change the last part to module for irregular number of sets
      return set_idx;
    }

  private:
    uint32_t num_set, num_way;
};

class MultiplicativeHash : public IndexHash 
{
  public:
    MultiplicativeHash(uint32_t _num_set, uint32_t _num_way) : num_set(_num_set), num_way(_num_way) {}
    
    virtual ~MultiplicativeHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      uint64_t block = address >> 6;
      uint64_t hash = (block * 0x9E3779B97F4A7C15) >> (64 - champsim::lg2(num_set));
      return static_cast<uint32_t>(hash);
    }

  private:
    uint32_t num_set, num_way;
};

/*************
 * Replacement policy interface and implementations
 *************/
class ReplacementPolicy 
{  
  public:

    struct REP_POL_ARGS 
    {
      uint64_t access_freq;
      uint8_t pte_level;
      uint64_t pc;           // program counter associated with this access
      uint64_t pte_address;  // address of the PTE being accessed
      bool is_prefetch;      // whether the access was generated by prefetch

      REP_POL_ARGS()
        : access_freq(0), pte_level(0), pc(0), pte_address(0), is_prefetch(false)
      {}
    };

    virtual ~ReplacementPolicy() = default;	
    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t curr_cycle, bool hit, REP_POL_ARGS xargs) = 0;
    virtual uint32_t find_victim(uint32_t set_idx) = 0; 
};


class LFU : public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    uint32_t lfu_counter_bits;
    uint64_t lfu_counter_max;

  public:
    LFU(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) {
      std::cout << "Using LFU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      // Read counter bits from environment variable
      const char* bits_env = getenv("TXVC_REP_LFU_BITS");
      if (bits_env != nullptr) {
        lfu_counter_bits = std::stoi(bits_env);
        if (lfu_counter_bits == 0 || lfu_counter_bits > 64) {
          std::cerr << "TXVC_REP_LFU_BITS invalid or out of range (1-64), using default 8 bits." << std::endl;
          lfu_counter_bits = 8;
        }
      } else {
        lfu_counter_bits = 8;
      }
      lfu_counter_max = (lfu_counter_bits == 64) ? UINT64_MAX : ((1ULL << lfu_counter_bits) - 1);
      std::cout << "\tLFU counter bits: " << lfu_counter_bits << " (max value: " << lfu_counter_max << ")" << std::endl;
      freq_ctr.resize(num_set * num_way, 0);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS) {
      size_t idx = set_idx * num_way + way_idx;
      if (hit) {
        if (freq_ctr[idx] < lfu_counter_max) {
          freq_ctr[idx]++;
        }
      } else {
        freq_ctr[idx] = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx) {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};


class LFUPP : public ReplacementPolicy 
{
  private:
      
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
  
  public: 

    LFUPP(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using LFU++ replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      freq_ctr.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) {
        //std::cout << "LFU: Increasing idx @ " << set_idx << " set."  << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = xargs.access_freq;
      }  else { 
        //std::cout << "LFU: Resetting idx @ " << set_idx << " set." << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LFU: frequency counter for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
	    //std::cout << "LFU:victim:" << victim_idx << std::endl;
	    return victim_idx;
    }
};

class LFUwDecay : public ReplacementPolicy 
{
  private:
      
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    uint64_t DECAY_VALUE; // the right shift value applied to the frequency counter to implement decay. Higher values mean more aggressive decay
  
  public: 

    LFUwDecay(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using LFU with Decay replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;


			if (getenv("TXVC_REP_DECAY") != nullptr) {
					DECAY_VALUE = std::stoi(getenv("TXVC_REP_DECAY"));
			} else {
          std::cerr << "TXVC_REP_DECAY not set! Using default value of 1." << std::endl;
          DECAY_VALUE = 1;
      }

      std::cout << "\tDecay applied on frequency counters: " << DECAY_VALUE << std::endl;
      freq_ctr.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) {
        //std::cout << "LFU: Increasing idx @ " << set_idx << " set."  << std::endl;
        uint64_t current_freq = freq_ctr.at(set_idx * num_way + way_idx);
        current_freq = std::max<uint64_t>(1, static_cast<uint64_t>(current_freq) >> DECAY_VALUE); // apply decay to the current frequency counter value
        freq_ctr.at(set_idx * num_way + way_idx) = current_freq + 1;
      }  else { 
        //std::cout << "LFU: Resetting idx @ " << set_idx << " set." << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LFU: frequency counter for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
	    //std::cout << "LFU:victim:" << victim_idx << std::endl;
	    return victim_idx;
    }
};


class LRFU : public ReplacementPolicy
{
  private:
    uint64_t num_set, num_way;
    std::vector<double> score;           // decaying combined recency/frequency score per line
    std::vector<uint64_t> last_access;   // last cycle when the entry was updated
    double DECAY_FACTOR; // between 0 and 1, higher means slower decay (more frequency-biased)
  
  public:
    
    LRFU(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)
    {
      std::cout << "Using LRFU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;

      // read decay factor from environment (TXVC_REP_DECAY used for all
      // victim-cache replacement policies). Default to 0.9
      if (getenv("TXVC_REP_DECAY") != nullptr) {
        DECAY_FACTOR = std::atof(getenv("TXVC_REP_DECAY"));
        if (DECAY_FACTOR <= 0.0 || DECAY_FACTOR >= 1.0) {
          std::cerr << "Invalid TXVC_REP_DECAY; must be in (0,1). Using default 0.9" << std::endl;
          DECAY_FACTOR = 0.9;
        }
      } else {
        DECAY_FACTOR = 0.9;
      }

      std::cout << "\tDecay factor: " << DECAY_FACTOR << std::endl;
      score.resize(num_set * num_way);
      last_access.resize(num_set * num_way);
    }

    // Update: called on hits and on victimization.  We age the slot by the
    // number of cycles elapsed since its last update, then bump it if it's a hit.
    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,
                                          uint64_t curr_cycle, bool hit,
                                          REP_POL_ARGS)
    {
      uint64_t idx = set_idx * num_way + way_idx;
      if (hit) {
        uint64_t delta = curr_cycle - last_access[idx];
        if (delta > 0) {
          // exponential decay over elapsed cycles
          score[idx] *= std::pow(DECAY_FACTOR, (double)delta);
        }
        score[idx] += 1.0;
        last_access[idx] = curr_cycle;
      } else {
        // victim being evicted; reset score for incoming block
        score[idx] = 0.0;
        last_access[idx] = curr_cycle;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(score), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way with the lowest score (least recently/frequently used)
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim));
      return victim_idx;
    }

};


// LFU variant that periodically right-shifts all frequency counters by 1.
// The halving interval is controlled by TXVC_REP_HALVE_PERIOD (in cycles); default is 100000.
class LFU_Halving : public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    uint64_t HALVE_PERIOD;
    uint64_t next_halve;

  public:
    LFU_Halving(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)
    {
      std::cout << "Using LFU_Halving replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;

      freq_ctr.resize(num_set * num_way);

      if (getenv("TXVC_REP_HALVE_PERIOD") != nullptr) {
        HALVE_PERIOD = std::stoull(getenv("TXVC_REP_HALVE_PERIOD"));
      } else {
        HALVE_PERIOD = 100000; // default
      }
      next_halve = HALVE_PERIOD;
      std::cout << "\tHalve period: " << HALVE_PERIOD << std::endl;
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,
                                          uint64_t curr_cycle, bool hit,
                                          REP_POL_ARGS)
    {
      if (curr_cycle >= next_halve) {
        for (uint64_t &val : freq_ctr)
          val >>= 1;
        next_halve = curr_cycle + HALVE_PERIOD;
      }
      if (hit) {
        freq_ctr.at(set_idx * num_way + way_idx)++;
      } else {
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::min_element(begin, end);
      assert(begin <= victim && victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};


class LRU_Halving : public ReplacementPolicy 
{

  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> last_used_cycles;
    uint64_t HALVE_PERIOD;
    uint64_t next_halve;

  public:
    LRU_Halving(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)
    {
      std::cout << "Using LRU_Halving replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;

      last_used_cycles.resize(num_set * num_way);

      if (getenv("TXVC_REP_HALVE_PERIOD") != nullptr) {
        HALVE_PERIOD = std::stoull(getenv("TXVC_REP_HALVE_PERIOD"));
      } else {
        HALVE_PERIOD = 100000; // default
      }
      next_halve = 0;
      std::cout << "\tHalve period: " << HALVE_PERIOD << std::endl;
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,
                                          uint64_t curr_cycle, bool hit,
                                          REP_POL_ARGS)
    {
      if (curr_cycle >= next_halve) {
        for (uint64_t &val : last_used_cycles)
          val >>= 1;
        next_halve = curr_cycle + HALVE_PERIOD;
      }
      if (!hit) { // only update on fills/evictions
        last_used_cycles.at(set_idx * num_way + way_idx) = curr_cycle;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(last_used_cycles), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::min_element(begin, end);
      assert(begin <= victim && victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};

// LFU with PC-hotness tie-breaking.  A global hotness counter is
// maintained per PC; victims are picked to minimize (freq * hotness).
class LFU_PCHot : public ReplacementPolicy {
  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    std::vector<uint64_t> slot_pc;
    std::unordered_map<uint64_t,uint64_t> pc_hotness;
    uint64_t reset_interval;   // number of updates between hotness resets
    uint64_t update_count;     // count of calls to update_replacement_state

  public:
    LFU_PCHot(uint64_t _num_set, uint64_t _num_way)
      : num_set(_num_set), num_way(_num_way), update_count(0) {
      std::cout << "Using LFU+PC-hotness replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      freq_ctr.resize(num_set * num_way);
      slot_pc.resize(num_set * num_way);
      // read reset interval from environment
      if (getenv("TXVC_REP_PC_RESET_INTERVAL") != nullptr) {
        reset_interval = std::stoull(getenv("TXVC_REP_PC_RESET_INTERVAL"));
      } else {
        reset_interval = 100000; // default value
      }
      std::cout << "\tPC hotness reset interval: " << reset_interval << " updates" << std::endl;
    }

    virtual void update_replacement_state(uint32_t set_idx,
                                          uint32_t way_idx,
                                          uint64_t /*curr_cycle*/,
                                          bool hit,
                                          REP_POL_ARGS xargs) override
    {
      // global reset based on number of updates
      if (++update_count >= reset_interval) {
        for (auto &kv : pc_hotness)
          kv.second = 0;
        update_count = 0;
      }

      uint64_t idx = set_idx * num_way + way_idx;
      if (hit) {
        // hit always comes with a valid PC
        freq_ctr[idx]++;
        slot_pc[idx] = xargs.pc;
        pc_hotness[xargs.pc]++;
      } else {
        // fill: decrement hotness of outgoing PC, if any
        uint64_t old_pc = slot_pc[idx];
        if (old_pc) {
          auto &hot = pc_hotness[old_pc];
          if (hot > 0) hot--;
        }
        // install new entry
        freq_ctr[idx] = 1;
        slot_pc[idx] = xargs.pc;
        pc_hotness[xargs.pc]++;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx) override
    {
      uint32_t victim = 0;
      uint64_t min_score = UINT64_MAX;
      for (uint32_t w = 0; w < num_way; ++w) {
        uint64_t idx = set_idx * num_way + w;
        uint64_t f = freq_ctr[idx];
        uint64_t pc = slot_pc[idx];
        uint64_t hot = 1;
        auto it = pc_hotness.find(pc);
        if (it != pc_hotness.end())
          hot = it->second;
        uint64_t score = f * hot;
        if (score < min_score) {
          min_score = score;
          victim = w;
        }
      }
      return victim;
    }
};

class LRFU_WSS : public ReplacementPolicy

{

  private:

    uint64_t num_set, num_way;

    std::vector<uint64_t> freq_ctr;  // for LFU mode

    std::vector<uint64_t> last_used_cycles;  // for LRU mode

    uint64_t window_size;

    std::deque<bool> hit_history;

    uint64_t hit_count;

    double threshold;  // hit rate threshold to switch between LFU and LRU

  

  public:

    

    LRFU_WSS(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)

    {

      std::cout << "Using LRFU_WSS replacement policy for Victim Cache" << std::endl;

      std::cout << "\tNumber of sets: " << num_set << std::endl;

      std::cout << "\tNumber of ways: " << num_way << std::endl;

      if (getenv("TXVC_REP_THRESHOLD") != nullptr) {

        threshold = std::atof(getenv("TXVC_REP_THRESHOLD"));

        if (threshold < 0.0 || threshold > 1.0) {

          std::cerr << "Invalid TXVC_REP_THRESHOLD; must be in [0,1]. Using default 0.5" << std::endl;

          threshold = 0.5;

        }

      } else {

        threshold = 0.5;

      }

      if (getenv("TXVC_REP_WINDOW_SIZE") != nullptr) {

        window_size = std::stoull(getenv("TXVC_REP_WINDOW_SIZE"));

      } else {

        window_size = 1000;

      }

      std::cout << "\tHit rate threshold: " << threshold << std::endl;

      std::cout << "\tWindow size: " << window_size << std::endl;

      freq_ctr.resize(num_set * num_way);

      last_used_cycles.resize(num_set * num_way);

      hit_count = 0;

    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,

                                          uint64_t curr_cycle, bool hit,

                                          REP_POL_ARGS)

    {

      // Update hit history

      hit_history.push_back(hit);

      if (hit) hit_count++;

      if (hit_history.size() > window_size) {

        bool old_hit = hit_history.front();

        hit_history.pop_front();

        if (old_hit) hit_count--;

      }

      double hit_rate = hit_count / (double)hit_history.size();

      uint64_t idx = set_idx * num_way + way_idx;

      if (hit_rate > threshold) {

        // LFU mode: update frequency

        if (hit) {

          freq_ctr[idx]++;

        } else {

          freq_ctr[idx] = 0;

        }

      } else {

        // LRU mode: update recency

        if (!hit) {

          last_used_cycles[idx] = curr_cycle;

        }

      }

    }

    virtual uint32_t find_victim(uint32_t set_idx)

    {

      double hit_rate = hit_count / (double)hit_history.size();

      if (hit_rate > threshold) {

        // LFU victim: lowest frequency

        auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);

        auto end = std::next(begin, num_way);

        auto victim = std::min_element(begin, end);

        assert(begin <= victim && victim < end);

        return static_cast<uint32_t>(std::distance(begin, victim));

      } else {

        // LRU victim: least recently used

        auto begin = std::next(std::begin(last_used_cycles), set_idx * num_way);

        auto end = std::next(begin, num_way);

        auto victim = std::min_element(begin, end);

        assert(begin <= victim && victim < end);

        return static_cast<uint32_t>(std::distance(begin, victim));

      }

    }

};


class LRU : public ReplacementPolicy 
{
  private:

    uint32_t num_set, num_way;
    std::vector<uint64_t> last_used_cycles;

  public:
    LRU(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using LRU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      last_used_cycles.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t curr_cycle, bool hit, REP_POL_ARGS) 
    {
      // Mark the way as being used on the current cycle
      if (!hit) {// Skip this for writeback hits
        //std::cout << "LRU: Updating idx @ " << set_idx << " set." << std::endl;
        last_used_cycles.at(set_idx * num_way + way_idx) = curr_cycle;
      } 
    }

    virtual uint32_t find_victim(uint32_t set_idx) 
    {
      auto begin = std::next(std::begin(last_used_cycles), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use cycle is most distant
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      
      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LRU: last used cycle for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      auto victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
      //std::cout << "LRU:victim:" << victim_idx << std::endl;
      return victim_idx;
    }
};


class LFU_Leaf : public ReplacementPolicy // always prefer to evict the leaf ptes
{
  private:

    uint64_t num_set, num_way;
    std::vector<uint32_t> freq_ctr;
    std::vector<uint8_t> pte_level;
    uint8_t PTE_THRESHOLD; // consider lines with pte level >= this as leaf nodes and give them higher priority for eviction
    uint32_t ALLOWED_FREQ_DELTA;
    bool evict_leaf_nodes; // if true, will evict leaf nodes  instead of non-leaf nodes

  public: 

    LFU_Leaf(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
			if (getenv("TXVC_REP_PTE_THRESHOLD") != nullptr) {
					PTE_THRESHOLD = std::stoi(getenv("TXVC_REP_PTE_THRESHOLD"));
			} else {
          std::cerr << "TXVC_REP_PTE_THRESHOLD not set! Using default value of 2." << std::endl;
          PTE_THRESHOLD = 2;
      }

      evict_leaf_nodes = false;
      if (getenv("TXVC_REP_EVICT_LEAF_NODES") != nullptr) {
				char* cache_filtering_flag = getenv("TXVC_REP_EVICT_LEAF_NODES");
				if (strcmp(cache_filtering_flag, "true") == 0) {
					evict_leaf_nodes = true;
				}
      } else {
        std::cerr << "TXVC_REP_EVICT_LEAF_NODES not defined!" << std::endl;
      }

			if (getenv("TXVC_REP_ALLOWED_FREQ_DELTA") != nullptr) {
					ALLOWED_FREQ_DELTA = std::stoi(getenv("TXVC_REP_ALLOWED_FREQ_DELTA"));
			} else {
          std::cerr << "TXVC_REP_ALLOWED_FREQ_DELTA not set! Using default value of 2." << std::endl;
          ALLOWED_FREQ_DELTA = 10;
      }

      std::cout << "Using LFU_Leaf replacement policy for Victim Cache" << std::endl;
      std::cout << "\tPTE threshold for leaf classification: " << PTE_THRESHOLD << std::endl;
      std::cout << "\tEvicting leaf nodes: " << (evict_leaf_nodes ? "true" : "false") << std::endl;
      std::cout << "\tAllowed frequency delta threshold: " << ALLOWED_FREQ_DELTA << std::endl;
      freq_ctr.resize(num_set * num_way);
      pte_level.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) freq_ctr.at(set_idx * num_way + way_idx) ++;
      else freq_ctr.at(set_idx * num_way + way_idx) = 0;

      pte_level.at(set_idx * num_way + way_idx) = xargs.pte_level;
    }


    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      uint32_t lfu_victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts

      // this is used to flip eviction from leaf to non-leaf nodes
      bool accepted_node_type = evict_leaf_nodes ? is_leaf(pte_level.at(lfu_victim_idx), PTE_THRESHOLD) : !is_leaf(pte_level.at(lfu_victim_idx), PTE_THRESHOLD);
      if (accepted_node_type) { // if the LFU victim is a leaf pte, evict it
        return lfu_victim_idx;
      }

      // if not, we need to check which is the least frequently used leaf pte and evict it instead
      uint32_t leaf_victim_idx = 0;
      bool alt_victim_found = false;
      uint64_t min_freq = UINT64_MAX;
      for (uint32_t i = 0; i < num_way; i++) {
        accepted_node_type = evict_leaf_nodes ? is_leaf(pte_level.at(set_idx * num_way + i), PTE_THRESHOLD) : !is_leaf(pte_level.at(set_idx * num_way + i), PTE_THRESHOLD);
        if (accepted_node_type && (freq_ctr.at(set_idx * num_way + i) < min_freq)) {
          min_freq = freq_ctr.at(set_idx * num_way + i);
          leaf_victim_idx = i;
          alt_victim_found = true;
        }
      }

      // also check that the alternative candidate is not much more frequetly used than the lfu one
      // WARN: we assume that since the node type was not accepted above, the substraction has to be possitive
      //       since the real lfu candidate is the one with the lowest value.
      uint32_t frequency_delta = min_freq - freq_ctr.at(lfu_victim_idx);
      if (alt_victim_found && (frequency_delta <= ALLOWED_FREQ_DELTA)) {
        return leaf_victim_idx;
      } else {
        return lfu_victim_idx;
      }
    }

    bool is_leaf(uint8_t level, uint8_t pte_level_threshold) {
      return level > pte_level_threshold;
    }
};



class SRRIP: public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV; //= 3 for 2-bit RRPV;
    std::vector<int> rrpv_values;
  
  public:
    // initialize replacement state
    SRRIP(uint64_t _num_set, uint64_t _num_way, int _maxRRPV) : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV)
    {
      std::cout << "Using SRRIP replacement policy for Victim Cache" << std::endl;
      rrpv_values = std::vector<int>(num_set * num_way, maxRRPV); 
    }

    // called on every cache hit and cache fill
    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS)
    {
      if (hit)
        rrpv_values[set_idx * num_way + way_idx] = 0;
      else
        rrpv_values[set_idx * num_way + way_idx] = maxRRPV - 1;
    }

    // find replacement victim
    uint32_t find_victim(uint32_t set_idx)
    {
      // look for the maxRRPV line
      auto begin = std::next(std::begin(rrpv_values), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::find(begin, end, maxRRPV); // hijack the lru field
      while (victim == end) {
        for (auto it = begin; it != end; ++it)
          ++(*it);

        victim = std::find(begin, end, maxRRPV);
      }

      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by assertions
    }
};


class SRRIP_Leaf: public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV; //= 3 for 2-bit RRPV;
    std::vector<int> rrpv_values;
    int PTE_THRESHOLD = 2; // consider lines with pte level >= this as leaf nodes and give them higher priority for eviction
    bool evict_leaf_nodes; // if true, will evict leaf nodes  instead of non-leaf nodes

  public:
    // initialize replacement state
    SRRIP_Leaf(uint64_t _num_set, uint64_t _num_way, int _maxRRPV) : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV)
    {

			if (getenv("TXVC_REP_PTE_THRESHOLD") != nullptr) {
					PTE_THRESHOLD = std::stoi(getenv("TXVC_REP_PTE_THRESHOLD"));
			} else {
          std::cerr << "TXVC_REP_PTE_THRESHOLD not set! Using default value of 2." << std::endl;
          PTE_THRESHOLD = 2;
      }

      evict_leaf_nodes = false;
      if (getenv("TXVC_REP_EVICT_LEAF_NODES") != nullptr) {
				char* cache_filtering_flag = getenv("TXVC_REP_EVICT_LEAF_NODES");
				if (strcmp(cache_filtering_flag, "true") == 0) {
					evict_leaf_nodes = true;
				}
      } else {
        std::cerr << "TXVC_REP_EVICT_LEAF_NODES not defined!" << std::endl;
      }

      std::cout << "Using SRRIP_Leaf replacement policy for Victim Cache" << std::endl;
      std::cout << "\tPTE threshold for leaf classification: " << PTE_THRESHOLD << std::endl;
      rrpv_values = std::vector<int>(num_set * num_way, maxRRPV); 
    }

    // called on every cache hit and cache fill
    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs)
    {

      bool accepted_node_type = evict_leaf_nodes ? !is_leaf(xargs.pte_level, PTE_THRESHOLD) : is_leaf(xargs.pte_level, PTE_THRESHOLD);
      if (hit)
        if (accepted_node_type)
          rrpv_values[set_idx * num_way + way_idx] = 0;
        else 
          rrpv_values[set_idx * num_way + way_idx] = 1;
      else
        if (accepted_node_type)
          rrpv_values[set_idx * num_way + way_idx] = maxRRPV - 2;
        else 
          rrpv_values[set_idx * num_way + way_idx] = maxRRPV - 1;
    }

    // find replacement victim
    uint32_t find_victim(uint32_t set_idx)
    {
      // look for the maxRRPV line
      auto begin = std::next(std::begin(rrpv_values), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::find(begin, end, maxRRPV); // hijack the lru field
      while (victim == end) {
        for (auto it = begin; it != end; ++it)
          ++(*it);

        victim = std::find(begin, end, maxRRPV);
      }

      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by assertions
    }

    bool is_leaf(uint8_t level, uint8_t pte_level_threshold) {
      return level > pte_level_threshold;
    }
};


// PACIPV: Policy/Access-aware Cache Insertion & Promotion Vector.
// The vector has 5 entries:
//   idx 0..maxRRPV -> new RRPV on hit when old RRPV is idx
//   idx 4         -> insertion RRPV on fill
// This implementation keeps 2-bit RRPV semantics by default (maxRRPV = 3)
// and clamps all vector-provided values to [0, maxRRPV].
class PACIPV: public ReplacementPolicy
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV;
    std::vector<uint8_t> rrpv_values;

    static constexpr std::array<uint8_t, 5> DEFAULT_IPV = {0, 1, 1, 0, 3};
    std::array<uint8_t, 5> IPV;

    uint8_t clamp_rrpv(uint8_t v) const
    {
      return static_cast<uint8_t>(std::min<int>(v, maxRRPV));
    }

    std::array<uint8_t, 5> parse_ipv_bracket(const std::string& text,
                                             const std::array<uint8_t, 5>& fallback,
                                             int line_idx) const
    {
      auto start = text.find('[');
      auto end = text.find(']', start == std::string::npos ? 0 : start + 1);
      if (start == std::string::npos || end == std::string::npos || end <= start) {
        std::cerr << "PACIPV: Malformed IPV at index " << line_idx << ". Using default." << std::endl;
        return fallback;
      }
      ++start;
      std::string values = text.substr(start, end - start);
      std::array<uint8_t, 5> parsed = fallback;
      std::istringstream vss(values);
      std::string token;
      int v = 0;
      while (std::getline(vss, token, ',')) {
        if (v >= 5) {
          std::cerr << "PACIPV: Too many entries at index " << line_idx << ". Using default." << std::endl;
          return fallback;
        }
        try {
          int value = std::stoi(token);
          if (value < 0) {
            std::cerr << "PACIPV: Negative value at index " << line_idx << ". Using default." << std::endl;
            return fallback;
          }
          parsed[v++] = clamp_rrpv(static_cast<uint8_t>(value));
        } catch (...) {
          std::cerr << "PACIPV: Invalid entry at index " << line_idx << ". Using default." << std::endl;
          return fallback;
        }
      }
      if (v != 5) {
        std::cerr << "PACIPV: Too few entries at index " << line_idx << ". Using default." << std::endl;
        return fallback;
      }
      return parsed;
    }

    bool parse_ipv_from_file(const char* file_env, const char* idx_env,
                             std::array<uint8_t, 5>& out_ipv) const
    {
      const char* file_path = std::getenv(file_env);
      const char* idx_str   = std::getenv(idx_env);
      if (!file_path || !idx_str) {
        std::cerr << "PACIPV: " << file_env << " or " << idx_env << " not set. Using defaults." << std::endl;
        return false;
      }
      int target_idx = -1;
      try { target_idx = std::stoi(idx_str); }
      catch (...) {
        std::cerr << "PACIPV: Invalid index value in " << idx_env << ". Using defaults." << std::endl;
        return false;
      }
      std::ifstream infile(file_path);
      if (!infile) {
        std::cerr << "PACIPV: Could not open IPV pairs file: " << file_path << ". Using defaults." << std::endl;
        return false;
      }
      std::string line;
      while (std::getline(infile, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream linestream(line);
        int idx = -1;
        char colon;
        linestream >> idx >> colon;
        if (colon != ':' || idx != target_idx) continue;
        std::string rest;
        std::getline(linestream, rest);
        out_ipv = parse_ipv_bracket(rest, DEFAULT_IPV, target_idx);
        return true;
      }
      std::cerr << "PACIPV: Index " << target_idx << " not found in file. Using defaults." << std::endl;
      return false;
    }

    const std::array<uint8_t, 5>& select_ipv(const REP_POL_ARGS& xargs) const
    {
      static_cast<void>(xargs);
      return IPV;
    }

  public:
    PACIPV(uint64_t _num_set, uint64_t _num_way, int _maxRRPV = 3)
      : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV),
        rrpv_values(_num_set * _num_way, static_cast<uint8_t>(_maxRRPV)),
        IPV(DEFAULT_IPV)
    {
      // Load a single IPV from a file with lines in the format:
      //   INDEX: [v0,v1,v2,v3,v4]
      // Set TXVC_PACIPV_DEMAND_VECTOR_FILE and TXVC_PACIPV_DEMAND_VECTOR_IDX.
      // If those are not set, fall back to TXVC_PACIPV_DEMAND_VEC.
      if (!parse_ipv_from_file("TXVC_PACIPV_DEMAND_VECTOR_FILE",
                               "TXVC_PACIPV_DEMAND_VECTOR_IDX",
                               IPV)) {
        const char* env_value = std::getenv("TXVC_PACIPV_DEMAND_VEC");
        if (env_value != nullptr) {
          IPV = parse_ipv_bracket(env_value, DEFAULT_IPV, -1);
        }
      }

      std::cout << "Using PACIPV replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      std::cout << "\tMax RRPV: " << maxRRPV << std::endl;
      std::cout << "\tIPV: [" << static_cast<int>(IPV[0]) << ", " << static_cast<int>(IPV[1]) << ", "
                << static_cast<int>(IPV[2]) << ", " << static_cast<int>(IPV[3]) << ", "
                << static_cast<int>(IPV[4]) << "]" << std::endl;
    }

    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs) override
    {
      uint64_t idx = static_cast<uint64_t>(set_idx) * num_way + way_idx;
      const auto& ipv = select_ipv(xargs);

      if (hit) {
        uint8_t old_rrpv = clamp_rrpv(rrpv_values[idx]);
        rrpv_values[idx] = clamp_rrpv(ipv[old_rrpv]);
      } else {
        // insertion uses vector-defined insertion RRPV (entry 4)
        rrpv_values[idx] = clamp_rrpv(ipv[4]);
      }
    }

    uint32_t find_victim(uint32_t set_idx) override
    {
      auto begin = std::next(std::begin(rrpv_values), static_cast<uint64_t>(set_idx) * num_way);
      auto end = std::next(begin, num_way);

      while (true) {
        auto victim = std::find(begin, end, static_cast<uint8_t>(maxRRPV));
        if (victim != end) {
          return static_cast<uint32_t>(std::distance(begin, victim));
        }

        // Age every line toward maxRRPV; saturate to avoid wrap-around.
        for (auto it = begin; it != end; ++it) {
          if (*it < static_cast<uint8_t>(maxRRPV))
            ++(*it);
        }
      }
    }
};


// PACIPV_LFU: PACIPV-style insertion/promotion vectors with LFU victim selection.
// The vector has 5 entries:
//   idx 0..maxRRPV -> new RRPV-like state on hit when old state is idx
//   idx 4         -> insertion state on fill
// We convert those states into LFU buckets where a higher bucket means "hotter".
class PACIPV_LFU: public ReplacementPolicy
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV;
    std::vector<uint8_t> freq_values;

    static constexpr std::array<uint8_t, 5> DEFAULT_IPV_DEMAND = {0, 1, 1, 0, 3};
    static constexpr std::array<uint8_t, 5> DEFAULT_IPV_PREFETCH = {0, 1, 0, 0, 3};
    std::array<uint8_t, 5> IPV_DEMAND;
    std::array<uint8_t, 5> IPV_PREFETCH;

    uint8_t clamp_rrpv(uint8_t v) const
    {
      return static_cast<uint8_t>(std::min<int>(v, maxRRPV));
    }

    std::array<uint8_t, 5> parse_ipv_env(const char* env_name, const std::array<uint8_t, 5>& fallback) const
    {
      const char* env_value = std::getenv(env_name);
      if (env_value == nullptr)
        return fallback;

      std::string raw(env_value);
      if (!raw.empty() && raw.front() == '[') raw.erase(raw.begin());
      if (!raw.empty() && raw.back() == ']') raw.pop_back();

      std::array<uint8_t, 5> parsed = fallback;
      std::stringstream ss(raw);
      std::string token;
      int idx = 0;

      while (std::getline(ss, token, ',')) {
        if (idx >= 5) {
          std::cerr << env_name << " has more than 5 entries. Using default." << std::endl;
          return fallback;
        }

        try {
          int value = std::stoi(token);
          if (value < 0) {
            std::cerr << env_name << " contains negative value. Using default." << std::endl;
            return fallback;
          }
          parsed[idx++] = clamp_rrpv(static_cast<uint8_t>(value));
        } catch (...) {
          std::cerr << env_name << " contains invalid entry. Using default." << std::endl;
          return fallback;
        }
      }

      if (idx != 5) {
        std::cerr << env_name << " must provide exactly 5 comma-separated values. Using default." << std::endl;
        return fallback;
      }

      return parsed;
    }

    uint8_t clamp_freq(uint8_t v) const
    {
      return static_cast<uint8_t>(std::min<int>(v, maxRRPV));
    }

    const std::array<uint8_t, 5>& select_ipv(const REP_POL_ARGS& xargs) const
    {
      return xargs.is_prefetch ? IPV_PREFETCH : IPV_DEMAND;
    }

    uint8_t rrpv_from_freq(uint8_t freq) const
    {
      return static_cast<uint8_t>(maxRRPV - clamp_freq(freq));
    }

    uint8_t freq_from_rrpv(uint8_t rrpv) const
    {
      return static_cast<uint8_t>(maxRRPV - clamp_rrpv(rrpv));
    }

  public:
    PACIPV_LFU(uint64_t _num_set, uint64_t _num_way, int _maxRRPV = 3)
      : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV), freq_values(_num_set * _num_way, 0),
        IPV_DEMAND(parse_ipv_env("TXVC_PACIPV_DEMAND_VEC", DEFAULT_IPV_DEMAND)),
        IPV_PREFETCH(parse_ipv_env("TXVC_PACIPV_PREFETCH_VEC", DEFAULT_IPV_PREFETCH))
    {
      std::cout << "Using PACIPV_LFU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      std::cout << "\tMax RRPV/Frequency bucket: " << maxRRPV << std::endl;
      std::cout << "\tDemand IPV: [" << static_cast<int>(IPV_DEMAND[0]) << ", " << static_cast<int>(IPV_DEMAND[1]) << ", "
                << static_cast<int>(IPV_DEMAND[2]) << ", " << static_cast<int>(IPV_DEMAND[3]) << ", "
                << static_cast<int>(IPV_DEMAND[4]) << "]" << std::endl;
      std::cout << "\tPrefetch IPV: [" << static_cast<int>(IPV_PREFETCH[0]) << ", " << static_cast<int>(IPV_PREFETCH[1]) << ", "
                << static_cast<int>(IPV_PREFETCH[2]) << ", " << static_cast<int>(IPV_PREFETCH[3]) << ", "
                << static_cast<int>(IPV_PREFETCH[4]) << "]" << std::endl;
    }

    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs) override
    {
      uint64_t idx = static_cast<uint64_t>(set_idx) * num_way + way_idx;
      const auto& ipv = select_ipv(xargs);

      if (hit) {
        uint8_t old_rrpv = rrpv_from_freq(freq_values[idx]);
        uint8_t new_rrpv = clamp_rrpv(ipv[old_rrpv]);
        freq_values[idx] = freq_from_rrpv(new_rrpv);
      } else {
        // insertion uses vector-defined insertion state (entry 4)
        freq_values[idx] = freq_from_rrpv(ipv[4]);
      }
    }

    uint32_t find_victim(uint32_t set_idx) override
    {
      auto begin = std::next(std::begin(freq_values), static_cast<uint64_t>(set_idx) * num_way);
      auto end = std::next(begin, num_way);

      // LFU victim: evict the coldest line (lowest frequency bucket).
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};


class HREP : public ReplacementPolicy 
{
  private:
      
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
  
  public: 

    HREP(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using HREP replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      freq_ctr.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) {
        //std::cout << "LFU: Increasing idx @ " << set_idx << " set."  << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) ++;
      }  else { 
        //std::cout << "LFU: Resetting idx @ " << set_idx << " set." << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LFU: frequency counter for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
	    //std::cout << "LFU:victim:" << victim_idx << std::endl;
	    return victim_idx;
    }
};

#endif