#ifndef VICTIM_CACHE_H
#define VICTIM_CACHE_H

#include <iostream>
#include <algorithm>
#include <array>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <unordered_map>
#include <deque>

#include "champsim.h"


class IndexHash
{
  public:
    
    virtual ~IndexHash() = default;
    
    virtual uint32_t get_set(uint64_t address) = 0; 

};

class DefaultHash : public IndexHash
{
  public:
    DefaultHash(uint32_t _num_set, uint32_t _num_way, uint32_t _offset_bits) : num_set(_num_set), num_way(_num_way), offset_bits(_offset_bits) {}
    
    virtual ~DefaultHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      return (address >> offset_bits) & champsim::bitmask(champsim::lg2(num_set));
    }

  private:
    uint32_t num_set, num_way, offset_bits;
};


class ModuloHash : public IndexHash 
{
  public:
    ModuloHash(uint32_t _num_set, uint32_t _num_way, uint32_t _offset_bits) : num_set(_num_set), num_way(_num_way), offset_bits(_offset_bits) {}
    
    virtual ~ModuloHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      return (address >> offset_bits) & champsim::bitmask(champsim::lg2(num_set));
    }

  private:
    uint32_t num_set, num_way, offset_bits;
};

class XORHash : public IndexHash
{
  public:
    XORHash(uint32_t _num_set, uint32_t _num_way) : num_set(_num_set), num_way(_num_way) {}
    
    virtual ~XORHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      uint64_t block = address >> 6;
      uint32_t set_idx = (block ^ (block >> 7) ^ (block >> 13)) & (num_set - 1); 
      // we can change the last part to module for irregular number of sets
      return set_idx;
    }

  private:
    uint32_t num_set, num_way;
};

class MultiplicativeHash : public IndexHash 
{
  public:
    MultiplicativeHash(uint32_t _num_set, uint32_t _num_way) : num_set(_num_set), num_way(_num_way) {}
    
    virtual ~MultiplicativeHash() = default;
    
    uint32_t get_set(uint64_t address) 
    {
      uint64_t block = address >> 6;
      uint64_t hash = (block * 0x9E3779B97F4A7C15) >> (64 - champsim::lg2(num_set));
      return static_cast<uint32_t>(hash);
    }

  private:
    uint32_t num_set, num_way;
};

/*************
 * Replacement policy interface and implementations
 *************/
class ReplacementPolicy 
{  
  public:

    struct REP_POL_ARGS 
    {
      uint64_t access_freq;
      uint8_t pte_level;
      uint64_t pc;           // program counter associated with this access
      uint64_t pte_address;  // address of the PTE being accessed
      bool is_prefetch;      // whether the access was generated by prefetch

      REP_POL_ARGS()
        : access_freq(0), pte_level(0), pc(0), pte_address(0), is_prefetch(false)
      {}
    };

    virtual ~ReplacementPolicy() = default;	
    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t curr_cycle, bool hit, REP_POL_ARGS xargs) = 0;
    virtual uint32_t find_victim(uint32_t set_idx) = 0; 
};


class LFU : public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    uint32_t lfu_counter_bits;
    uint64_t lfu_counter_max;

  public:
    LFU(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) {
      std::cout << "Using LFU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      // Read counter bits from environment variable
      const char* bits_env = getenv("TXVC_LFU_CNTR_BITS");
      if (bits_env != nullptr) {
        lfu_counter_bits = std::stoi(bits_env);
        if (lfu_counter_bits == 0 || lfu_counter_bits > 64) {
          std::cerr << "TXVC_LFU_CNTR_BITS invalid or out of range (1-64), using default 8 bits." << std::endl;
          lfu_counter_bits = 8;
        }
      } else {
        lfu_counter_bits = 8;
      }
      lfu_counter_max = (lfu_counter_bits == 64) ? UINT64_MAX : ((1ULL << lfu_counter_bits) - 1);
      std::cout << "\tLFU counter bits: " << lfu_counter_bits << " (max value: " << lfu_counter_max << ")" << std::endl;
      freq_ctr.resize(num_set * num_way, 0);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS) {
      size_t idx = set_idx * num_way + way_idx;
      if (hit) {
        if (freq_ctr[idx] < lfu_counter_max) {
          freq_ctr[idx]++;
        }
      } else {
        freq_ctr[idx] = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx) {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};


class LFUPP : public ReplacementPolicy 
{
  private:
      
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
  
  public: 

    LFUPP(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using LFU++ replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      freq_ctr.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) {
        //std::cout << "LFU: Increasing idx @ " << set_idx << " set."  << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = xargs.access_freq;
      }  else { 
        //std::cout << "LFU: Resetting idx @ " << set_idx << " set." << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LFU: frequency counter for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
	    //std::cout << "LFU:victim:" << victim_idx << std::endl;
	    return victim_idx;
    }
};

class LFUwDecay : public ReplacementPolicy 
{
  private:
      
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    uint64_t DECAY_VALUE; // the right shift value applied to the frequency counter to implement decay. Higher values mean more aggressive decay
  
  public: 

    LFUwDecay(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using LFU with Decay replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;


			if (getenv("TXVC_REP_DECAY") != nullptr) {
					DECAY_VALUE = std::stoi(getenv("TXVC_REP_DECAY"));
			} else {
          std::cerr << "TXVC_REP_DECAY not set! Using default value of 1." << std::endl;
          DECAY_VALUE = 1;
      }

      std::cout << "\tDecay applied on frequency counters: " << DECAY_VALUE << std::endl;
      freq_ctr.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) {
        //std::cout << "LFU: Increasing idx @ " << set_idx << " set."  << std::endl;
        uint64_t current_freq = freq_ctr.at(set_idx * num_way + way_idx);
        current_freq = std::max<uint64_t>(1, static_cast<uint64_t>(current_freq) >> DECAY_VALUE); // apply decay to the current frequency counter value
        freq_ctr.at(set_idx * num_way + way_idx) = current_freq + 1;
      }  else { 
        //std::cout << "LFU: Resetting idx @ " << set_idx << " set." << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LFU: frequency counter for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
	    //std::cout << "LFU:victim:" << victim_idx << std::endl;
	    return victim_idx;
    }
};


class LRFU : public ReplacementPolicy
{
  private:
    uint64_t num_set, num_way;
    std::vector<double> score;           // decaying combined recency/frequency score per line
    std::vector<uint64_t> last_access;   // last cycle when the entry was updated
    double DECAY_FACTOR; // between 0 and 1, higher means slower decay (more frequency-biased)
  
  public:
    
    LRFU(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)
    {
      std::cout << "Using LRFU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;

      // read decay factor from environment (TXVC_REP_DECAY used for all
      // victim-cache replacement policies). Default to 0.9
      if (getenv("TXVC_REP_DECAY") != nullptr) {
        DECAY_FACTOR = std::atof(getenv("TXVC_REP_DECAY"));
        if (DECAY_FACTOR <= 0.0 || DECAY_FACTOR >= 1.0) {
          std::cerr << "Invalid TXVC_REP_DECAY; must be in (0,1). Using default 0.9" << std::endl;
          DECAY_FACTOR = 0.9;
        }
      } else {
        DECAY_FACTOR = 0.9;
      }

      std::cout << "\tDecay factor: " << DECAY_FACTOR << std::endl;
      score.resize(num_set * num_way);
      last_access.resize(num_set * num_way);
    }

    // Update: called on hits and on victimization.  We age the slot by the
    // number of cycles elapsed since its last update, then bump it if it's a hit.
    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,
                                          uint64_t curr_cycle, bool hit,
                                          REP_POL_ARGS)
    {
      uint64_t idx = set_idx * num_way + way_idx;
      if (hit) {
        uint64_t delta = curr_cycle - last_access[idx];
        if (delta > 0) {
          // exponential decay over elapsed cycles
          score[idx] *= std::pow(DECAY_FACTOR, (double)delta);
        }
        score[idx] += 1.0;
        last_access[idx] = curr_cycle;
      } else {
        // victim being evicted; reset score for incoming block
        score[idx] = 0.0;
        last_access[idx] = curr_cycle;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(score), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way with the lowest score (least recently/frequently used)
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim));
      return victim_idx;
    }

};


// LFU variant that periodically right-shifts all frequency counters by 1.
// The halving interval is controlled by TXVC_REP_HALVE_PERIOD (in cycles); default is 100000.
class LFU_Halving : public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    uint64_t HALVE_PERIOD;
    uint64_t next_halve;

  public:
    LFU_Halving(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)
    {
      std::cout << "Using LFU_Halving replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;

      freq_ctr.resize(num_set * num_way);

      if (getenv("TXVC_REP_HALVE_PERIOD") != nullptr) {
        HALVE_PERIOD = std::stoull(getenv("TXVC_REP_HALVE_PERIOD"));
      } else {
        HALVE_PERIOD = 100000; // default
      }
      next_halve = HALVE_PERIOD;
      std::cout << "\tHalve period: " << HALVE_PERIOD << std::endl;
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,
                                          uint64_t curr_cycle, bool hit,
                                          REP_POL_ARGS)
    {
      if (curr_cycle >= next_halve) {
        for (uint64_t &val : freq_ctr)
          val >>= 1;
        next_halve = curr_cycle + HALVE_PERIOD;
      }
      if (hit) {
        freq_ctr.at(set_idx * num_way + way_idx)++;
      } else {
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::min_element(begin, end);
      assert(begin <= victim && victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};


class LRU_Halving : public ReplacementPolicy 
{

  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> last_used_cycles;
    uint64_t HALVE_PERIOD;
    uint64_t next_halve;

  public:
    LRU_Halving(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)
    {
      std::cout << "Using LRU_Halving replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;

      last_used_cycles.resize(num_set * num_way);

      if (getenv("TXVC_REP_HALVE_PERIOD") != nullptr) {
        HALVE_PERIOD = std::stoull(getenv("TXVC_REP_HALVE_PERIOD"));
      } else {
        HALVE_PERIOD = 100000; // default
      }
      next_halve = 0;
      std::cout << "\tHalve period: " << HALVE_PERIOD << std::endl;
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,
                                          uint64_t curr_cycle, bool hit,
                                          REP_POL_ARGS)
    {
      if (curr_cycle >= next_halve) {
        for (uint64_t &val : last_used_cycles)
          val >>= 1;
        next_halve = curr_cycle + HALVE_PERIOD;
      }
      if (!hit) { // only update on fills/evictions
        last_used_cycles.at(set_idx * num_way + way_idx) = curr_cycle;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(last_used_cycles), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::min_element(begin, end);
      assert(begin <= victim && victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim));
    }
};

// LFU with PC-hotness tie-breaking.  A global hotness counter is
// maintained per PC; victims are picked to minimize (freq * hotness).
class LFU_PCHot : public ReplacementPolicy {
  private:
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
    std::vector<uint64_t> slot_pc;
    std::unordered_map<uint64_t,uint64_t> pc_hotness;
    uint64_t reset_interval;   // number of updates between hotness resets
    uint64_t update_count;     // count of calls to update_replacement_state

  public:
    LFU_PCHot(uint64_t _num_set, uint64_t _num_way)
      : num_set(_num_set), num_way(_num_way), update_count(0) {
      std::cout << "Using LFU+PC-hotness replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      freq_ctr.resize(num_set * num_way);
      slot_pc.resize(num_set * num_way);
      // read reset interval from environment
      if (getenv("TXVC_REP_PC_RESET_INTERVAL") != nullptr) {
        reset_interval = std::stoull(getenv("TXVC_REP_PC_RESET_INTERVAL"));
      } else {
        reset_interval = 100000; // default value
      }
      std::cout << "\tPC hotness reset interval: " << reset_interval << " updates" << std::endl;
    }

    virtual void update_replacement_state(uint32_t set_idx,
                                          uint32_t way_idx,
                                          uint64_t /*curr_cycle*/,
                                          bool hit,
                                          REP_POL_ARGS xargs) override
    {
      // global reset based on number of updates
      if (++update_count >= reset_interval) {
        for (auto &kv : pc_hotness)
          kv.second = 0;
        update_count = 0;
      }

      uint64_t idx = set_idx * num_way + way_idx;
      if (hit) {
        // hit always comes with a valid PC
        freq_ctr[idx]++;
        slot_pc[idx] = xargs.pc;
        pc_hotness[xargs.pc]++;
      } else {
        // fill: decrement hotness of outgoing PC, if any
        uint64_t old_pc = slot_pc[idx];
        if (old_pc) {
          auto &hot = pc_hotness[old_pc];
          if (hot > 0) hot--;
        }
        // install new entry
        freq_ctr[idx] = 1;
        slot_pc[idx] = xargs.pc;
        pc_hotness[xargs.pc]++;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx) override
    {
      uint32_t victim = 0;
      uint64_t min_score = UINT64_MAX;
      for (uint32_t w = 0; w < num_way; ++w) {
        uint64_t idx = set_idx * num_way + w;
        uint64_t f = freq_ctr[idx];
        uint64_t pc = slot_pc[idx];
        uint64_t hot = 1;
        auto it = pc_hotness.find(pc);
        if (it != pc_hotness.end())
          hot = it->second;
        uint64_t score = f * hot;
        if (score < min_score) {
          min_score = score;
          victim = w;
        }
      }
      return victim;
    }
};

class LRFU_WSS : public ReplacementPolicy

{

  private:

    uint64_t num_set, num_way;

    std::vector<uint64_t> freq_ctr;  // for LFU mode

    std::vector<uint64_t> last_used_cycles;  // for LRU mode

    uint64_t window_size;

    std::deque<bool> hit_history;

    uint64_t hit_count;

    double threshold;  // hit rate threshold to switch between LFU and LRU

  

  public:

    

    LRFU_WSS(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way)

    {

      std::cout << "Using LRFU_WSS replacement policy for Victim Cache" << std::endl;

      std::cout << "\tNumber of sets: " << num_set << std::endl;

      std::cout << "\tNumber of ways: " << num_way << std::endl;

      if (getenv("TXVC_REP_THRESHOLD") != nullptr) {

        threshold = std::atof(getenv("TXVC_REP_THRESHOLD"));

        if (threshold < 0.0 || threshold > 1.0) {

          std::cerr << "Invalid TXVC_REP_THRESHOLD; must be in [0,1]. Using default 0.5" << std::endl;

          threshold = 0.5;

        }

      } else {

        threshold = 0.5;

      }

      if (getenv("TXVC_REP_WINDOW_SIZE") != nullptr) {

        window_size = std::stoull(getenv("TXVC_REP_WINDOW_SIZE"));

      } else {

        window_size = 1000;

      }

      std::cout << "\tHit rate threshold: " << threshold << std::endl;

      std::cout << "\tWindow size: " << window_size << std::endl;

      freq_ctr.resize(num_set * num_way);

      last_used_cycles.resize(num_set * num_way);

      hit_count = 0;

    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx,

                                          uint64_t curr_cycle, bool hit,

                                          REP_POL_ARGS)

    {

      // Update hit history

      hit_history.push_back(hit);

      if (hit) hit_count++;

      if (hit_history.size() > window_size) {

        bool old_hit = hit_history.front();

        hit_history.pop_front();

        if (old_hit) hit_count--;

      }

      double hit_rate = hit_count / (double)hit_history.size();

      uint64_t idx = set_idx * num_way + way_idx;

      if (hit_rate > threshold) {

        // LFU mode: update frequency

        if (hit) {

          freq_ctr[idx]++;

        } else {

          freq_ctr[idx] = 0;

        }

      } else {

        // LRU mode: update recency

        if (!hit) {

          last_used_cycles[idx] = curr_cycle;

        }

      }

    }

    virtual uint32_t find_victim(uint32_t set_idx)

    {

      double hit_rate = hit_count / (double)hit_history.size();

      if (hit_rate > threshold) {

        // LFU victim: lowest frequency

        auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);

        auto end = std::next(begin, num_way);

        auto victim = std::min_element(begin, end);

        assert(begin <= victim && victim < end);

        return static_cast<uint32_t>(std::distance(begin, victim));

      } else {

        // LRU victim: least recently used

        auto begin = std::next(std::begin(last_used_cycles), set_idx * num_way);

        auto end = std::next(begin, num_way);

        auto victim = std::min_element(begin, end);

        assert(begin <= victim && victim < end);

        return static_cast<uint32_t>(std::distance(begin, victim));

      }

    }

};


class LRU : public ReplacementPolicy 
{
  private:

    uint32_t num_set, num_way;
    std::vector<uint64_t> last_used_cycles;

  public:
    LRU(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using LRU replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      last_used_cycles.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t curr_cycle, bool hit, REP_POL_ARGS) 
    {
      // Mark the way as being used on the current cycle
      if (!hit) {// Skip this for writeback hits
        //std::cout << "LRU: Updating idx @ " << set_idx << " set." << std::endl;
        last_used_cycles.at(set_idx * num_way + way_idx) = curr_cycle;
      } 
    }

    virtual uint32_t find_victim(uint32_t set_idx) 
    {
      auto begin = std::next(std::begin(last_used_cycles), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use cycle is most distant
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      
      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LRU: last used cycle for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      auto victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
      //std::cout << "LRU:victim:" << victim_idx << std::endl;
      return victim_idx;
    }
};


class LFU_Leaf : public ReplacementPolicy // always prefer to evict the leaf ptes
{
  private:

    uint64_t num_set, num_way;
    std::vector<uint32_t> freq_ctr;
    std::vector<uint8_t> pte_level;
    uint8_t PTE_THRESHOLD; // consider lines with pte level >= this as leaf nodes and give them higher priority for eviction
    uint32_t ALLOWED_FREQ_DELTA;
    bool evict_leaf_nodes; // if true, will evict leaf nodes  instead of non-leaf nodes

  public: 

    LFU_Leaf(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
			if (getenv("TXVC_REP_PTE_THRESHOLD") != nullptr) {
					PTE_THRESHOLD = std::stoi(getenv("TXVC_REP_PTE_THRESHOLD"));
			} else {
          std::cerr << "TXVC_REP_PTE_THRESHOLD not set! Using default value of 2." << std::endl;
          PTE_THRESHOLD = 2;
      }

      evict_leaf_nodes = false;
      if (getenv("TXVC_REP_EVICT_LEAF_NODES") != nullptr) {
				char* cache_filtering_flag = getenv("TXVC_REP_EVICT_LEAF_NODES");
				if (strcmp(cache_filtering_flag, "true") == 0) {
					evict_leaf_nodes = true;
				}
      } else {
        std::cerr << "TXVC_REP_EVICT_LEAF_NODES not defined!" << std::endl;
      }

			if (getenv("TXVC_REP_ALLOWED_FREQ_DELTA") != nullptr) {
					ALLOWED_FREQ_DELTA = std::stoi(getenv("TXVC_REP_ALLOWED_FREQ_DELTA"));
			} else {
          std::cerr << "TXVC_REP_ALLOWED_FREQ_DELTA not set! Using default value of 2." << std::endl;
          ALLOWED_FREQ_DELTA = 10;
      }

      std::cout << "Using LFU_Leaf replacement policy for Victim Cache" << std::endl;
      std::cout << "\tPTE threshold for leaf classification: " << PTE_THRESHOLD << std::endl;
      std::cout << "\tEvicting leaf nodes: " << (evict_leaf_nodes ? "true" : "false") << std::endl;
      std::cout << "\tAllowed frequency delta threshold: " << ALLOWED_FREQ_DELTA << std::endl;
      freq_ctr.resize(num_set * num_way);
      pte_level.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) freq_ctr.at(set_idx * num_way + way_idx) ++;
      else freq_ctr.at(set_idx * num_way + way_idx) = 0;

      pte_level.at(set_idx * num_way + way_idx) = xargs.pte_level;
    }


    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);
      uint32_t lfu_victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts

      // this is used to flip eviction from leaf to non-leaf nodes
      bool accepted_node_type = evict_leaf_nodes ? is_leaf(pte_level.at(lfu_victim_idx), PTE_THRESHOLD) : !is_leaf(pte_level.at(lfu_victim_idx), PTE_THRESHOLD);
      if (accepted_node_type) { // if the LFU victim is a leaf pte, evict it
        return lfu_victim_idx;
      }

      // if not, we need to check which is the least frequently used leaf pte and evict it instead
      uint32_t leaf_victim_idx = 0;
      bool alt_victim_found = false;
      uint64_t min_freq = UINT64_MAX;
      for (uint32_t i = 0; i < num_way; i++) {
        accepted_node_type = evict_leaf_nodes ? is_leaf(pte_level.at(set_idx * num_way + i), PTE_THRESHOLD) : !is_leaf(pte_level.at(set_idx * num_way + i), PTE_THRESHOLD);
        if (accepted_node_type && (freq_ctr.at(set_idx * num_way + i) < min_freq)) {
          min_freq = freq_ctr.at(set_idx * num_way + i);
          leaf_victim_idx = i;
          alt_victim_found = true;
        }
      }

      // also check that the alternative candidate is not much more frequetly used than the lfu one
      // WARN: we assume that since the node type was not accepted above, the substraction has to be possitive
      //       since the real lfu candidate is the one with the lowest value.
      uint32_t frequency_delta = min_freq - freq_ctr.at(lfu_victim_idx);
      if (alt_victim_found && (frequency_delta <= ALLOWED_FREQ_DELTA)) {
        return leaf_victim_idx;
      } else {
        return lfu_victim_idx;
      }
    }

    bool is_leaf(uint8_t level, uint8_t pte_level_threshold) {
      return level > pte_level_threshold;
    }
};



class SRRIP: public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV; //= 3 for 2-bit RRPV;
    std::vector<int> rrpv_values;
  
  public:
    // initialize replacement state
    SRRIP(uint64_t _num_set, uint64_t _num_way, int _maxRRPV) : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV)
    {
      std::cout << "Using SRRIP replacement policy for Victim Cache" << std::endl;
      rrpv_values = std::vector<int>(num_set * num_way, maxRRPV); 
    }

    // called on every cache hit and cache fill
    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS)
    {
      if (hit)
        rrpv_values[set_idx * num_way + way_idx] = 0;
      else
        rrpv_values[set_idx * num_way + way_idx] = maxRRPV - 1;
    }

    // find replacement victim
    uint32_t find_victim(uint32_t set_idx)
    {
      // look for the maxRRPV line
      auto begin = std::next(std::begin(rrpv_values), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::find(begin, end, maxRRPV); // hijack the lru field
      while (victim == end) {
        for (auto it = begin; it != end; ++it)
          ++(*it);

        victim = std::find(begin, end, maxRRPV);
      }

      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by assertions
    }
};


class SRRIP_Leaf: public ReplacementPolicy 
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV; //= 3 for 2-bit RRPV;
    std::vector<int> rrpv_values;
    int PTE_THRESHOLD = 2; // consider lines with pte level >= this as leaf nodes and give them higher priority for eviction
    bool evict_leaf_nodes; // if true, will evict leaf nodes  instead of non-leaf nodes

  public:
    // initialize replacement state
    SRRIP_Leaf(uint64_t _num_set, uint64_t _num_way, int _maxRRPV) : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV)
    {

			if (getenv("TXVC_REP_PTE_THRESHOLD") != nullptr) {
					PTE_THRESHOLD = std::stoi(getenv("TXVC_REP_PTE_THRESHOLD"));
			} else {
          std::cerr << "TXVC_REP_PTE_THRESHOLD not set! Using default value of 2." << std::endl;
          PTE_THRESHOLD = 2;
      }

      evict_leaf_nodes = false;
      if (getenv("TXVC_REP_EVICT_LEAF_NODES") != nullptr) {
				char* cache_filtering_flag = getenv("TXVC_REP_EVICT_LEAF_NODES");
				if (strcmp(cache_filtering_flag, "true") == 0) {
					evict_leaf_nodes = true;
				}
      } else {
        std::cerr << "TXVC_REP_EVICT_LEAF_NODES not defined!" << std::endl;
      }

      std::cout << "Using SRRIP_Leaf replacement policy for Victim Cache" << std::endl;
      std::cout << "\tPTE threshold for leaf classification: " << PTE_THRESHOLD << std::endl;
      rrpv_values = std::vector<int>(num_set * num_way, maxRRPV); 
    }

    // called on every cache hit and cache fill
    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs)
    {

      bool accepted_node_type = evict_leaf_nodes ? !is_leaf(xargs.pte_level, PTE_THRESHOLD) : is_leaf(xargs.pte_level, PTE_THRESHOLD);
      if (hit)
        if (accepted_node_type)
          rrpv_values[set_idx * num_way + way_idx] = 0;
        else 
          rrpv_values[set_idx * num_way + way_idx] = 1;
      else
        if (accepted_node_type)
          rrpv_values[set_idx * num_way + way_idx] = maxRRPV - 2;
        else 
          rrpv_values[set_idx * num_way + way_idx] = maxRRPV - 1;
    }

    // find replacement victim
    uint32_t find_victim(uint32_t set_idx)
    {
      // look for the maxRRPV line
      auto begin = std::next(std::begin(rrpv_values), set_idx * num_way);
      auto end = std::next(begin, num_way);
      auto victim = std::find(begin, end, maxRRPV); // hijack the lru field
      while (victim == end) {
        for (auto it = begin; it != end; ++it)
          ++(*it);

        victim = std::find(begin, end, maxRRPV);
      }

      assert(begin <= victim);
      assert(victim < end);
      return static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by assertions
    }

    bool is_leaf(uint8_t level, uint8_t pte_level_threshold) {
      return level > pte_level_threshold;
    }
};


// PACIPV: Policy/Access-aware Cache Insertion & Promotion Vector.
// The vector has 5 entries:
//   idx 0..maxRRPV -> new RRPV on hit when old RRPV is idx
//   idx 4         -> insertion RRPV on fill
// This implementation keeps 2-bit RRPV semantics by default (maxRRPV = 3)
// and clamps all vector-provided values to [0, maxRRPV].
class PACIPV: public ReplacementPolicy
{
  private:
    uint64_t num_set, num_way;
    int maxRRPV;
    std::vector<uint8_t> rrpv_values;

    static constexpr std::array<uint8_t, 5> DEFAULT_IPV = {0, 1, 1, 0, 3};
    std::array<uint8_t, 5> IPV;

    uint8_t clamp_rrpv(uint8_t v) const
    {
      return static_cast<uint8_t>(std::min<int>(v, maxRRPV));
    }

    std::array<uint8_t, 5> parse_ipv_bracket(const std::string& text,
                                             const std::array<uint8_t, 5>& fallback,
                                             int line_idx) const
    {
      auto start = text.find('[');
      auto end = text.find(']', start == std::string::npos ? 0 : start + 1);
      if (start == std::string::npos || end == std::string::npos || end <= start) {
        std::cerr << "PACIPV: Malformed IPV at index " << line_idx << ". Using default." << std::endl;
        return fallback;
      }
      ++start;
      std::string values = text.substr(start, end - start);
      std::array<uint8_t, 5> parsed = fallback;
      std::istringstream vss(values);
      std::string token;
      int v = 0;
      while (std::getline(vss, token, ',')) {
        if (v >= 5) {
          std::cerr << "PACIPV: Too many entries at index " << line_idx << ". Using default." << std::endl;
          return fallback;
        }
        try {
          int value = std::stoi(token);
          if (value < 0) {
            std::cerr << "PACIPV: Negative value at index " << line_idx << ". Using default." << std::endl;
            return fallback;
          }
          parsed[v++] = clamp_rrpv(static_cast<uint8_t>(value));
        } catch (...) {
          std::cerr << "PACIPV: Invalid entry at index " << line_idx << ". Using default." << std::endl;
          return fallback;
        }
      }
      if (v != 5) {
        std::cerr << "PACIPV: Too few entries at index " << line_idx << ". Using default." << std::endl;
        return fallback;
      }
      return parsed;
    }

    bool parse_ipv_from_file(const char* file_env, const char* idx_env,
                             std::array<uint8_t, 5>& out_ipv) const
    {
      const char* file_path = std::getenv(file_env);
      const char* idx_str   = std::getenv(idx_env);
      if (!file_path || !idx_str) {
        std::cerr << "PACIPV: " << file_env << " or " << idx_env << " not set. Using defaults." << std::endl;
        return false;
      }
      int target_idx = -1;
      try { target_idx = std::stoi(idx_str); }
      catch (...) {
        std::cerr << "PACIPV: Invalid index value in " << idx_env << ". Using defaults." << std::endl;
        return false;
      }
      std::ifstream infile(file_path);
      if (!infile) {
        std::cerr << "PACIPV: Could not open IPV pairs file: " << file_path << ". Using defaults." << std::endl;
        return false;
      }
      std::string line;
      while (std::getline(infile, line)) {
        if (line.empty() || line[0] == '#') continue;
        std::istringstream linestream(line);
        int idx = -1;
        char colon;
        linestream >> idx >> colon;
        if (colon != ':' || idx != target_idx) continue;
        std::string rest;
        std::getline(linestream, rest);
        out_ipv = parse_ipv_bracket(rest, DEFAULT_IPV, target_idx);
        return true;
      }
      std::cerr << "PACIPV: Index " << target_idx << " not found in file. Using defaults." << std::endl;
      return false;
    }

    const std::array<uint8_t, 5>& select_ipv(const REP_POL_ARGS& xargs) const
    {
      static_cast<void>(xargs);
      return IPV;
    }

  public:
    PACIPV(uint64_t _num_set, uint64_t _num_way, int _maxRRPV = 3)
      : num_set(_num_set), num_way(_num_way), maxRRPV(_maxRRPV),
        rrpv_values(_num_set * _num_way, static_cast<uint8_t>(_maxRRPV)),
        IPV(DEFAULT_IPV)
    {
      // Load a single IPV from a file with lines in the format:
      //   INDEX: [v0,v1,v2,v3,v4]
      // Set TXVC_PACIPV_DEMAND_VECTOR_FILE and TXVC_PACIPV_DEMAND_VECTOR_IDX.
      // If those are not set, fall back to TXVC_PACIPV_DEMAND_VEC.
      if (!parse_ipv_from_file("TXVC_PACIPV_DEMAND_VECTOR_FILE",
                               "TXVC_PACIPV_DEMAND_VECTOR_IDX",
                               IPV)) {
        const char* env_value = std::getenv("TXVC_PACIPV_DEMAND_VEC");
        if (env_value != nullptr) {
          IPV = parse_ipv_bracket(env_value, DEFAULT_IPV, -1);
        }
      }

      std::cout << "Using PACIPV replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      std::cout << "\tMax RRPV: " << maxRRPV << std::endl;
      std::cout << "\tIPV: [" << static_cast<int>(IPV[0]) << ", " << static_cast<int>(IPV[1]) << ", "
                << static_cast<int>(IPV[2]) << ", " << static_cast<int>(IPV[3]) << ", "
                << static_cast<int>(IPV[4]) << "]" << std::endl;
    }

    void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS xargs) override
    {
      uint64_t idx = static_cast<uint64_t>(set_idx) * num_way + way_idx;
      const auto& ipv = select_ipv(xargs);

      if (hit) {
        uint8_t old_rrpv = clamp_rrpv(rrpv_values[idx]);
        rrpv_values[idx] = clamp_rrpv(ipv[old_rrpv]);
      } else {
        // insertion uses vector-defined insertion RRPV (entry 4)
        rrpv_values[idx] = clamp_rrpv(ipv[4]);
      }
    }

    uint32_t find_victim(uint32_t set_idx) override
    {
      auto begin = std::next(std::begin(rrpv_values), static_cast<uint64_t>(set_idx) * num_way);
      auto end = std::next(begin, num_way);

      while (true) {
        auto victim = std::find(begin, end, static_cast<uint8_t>(maxRRPV));
        if (victim != end) {
          return static_cast<uint32_t>(std::distance(begin, victim));
        }

        // Age every line toward maxRRPV; saturate to avoid wrap-around.
        for (auto it = begin; it != end; ++it) {
          if (*it < static_cast<uint8_t>(maxRRPV))
            ++(*it);
        }
      }
    }
};


class HREP : public ReplacementPolicy 
{
  private:
      
    uint64_t num_set, num_way;
    std::vector<uint64_t> freq_ctr;
  
  public: 

    HREP(uint64_t _num_set, uint64_t _num_way) : num_set(_num_set), num_way(_num_way) 
    {
      std::cout << "Using HREP replacement policy for Victim Cache" << std::endl;
      std::cout << "\tNumber of sets: " << num_set << std::endl;
      std::cout << "\tNumber of ways: " << num_way << std::endl;
      freq_ctr.resize(num_set * num_way);
    }

    virtual void update_replacement_state(uint32_t set_idx, uint32_t way_idx, uint64_t, bool hit, REP_POL_ARGS)
    {
      // Mark the way as being used on the current cycle
      //if (hit && type == WRITE) { // Skip this for writeback hits
		  //  return;
      //} No writes for PTEs
       
      if (hit) {
        //std::cout << "LFU: Increasing idx @ " << set_idx << " set."  << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) ++;
      }  else { 
        //std::cout << "LFU: Resetting idx @ " << set_idx << " set." << std::endl;
        freq_ctr.at(set_idx * num_way + way_idx) = 0;
      }
    }

    virtual uint32_t find_victim(uint32_t set_idx)
    {
      auto begin = std::next(std::begin(freq_ctr), set_idx * num_way);
      auto end = std::next(begin, num_way);

      // Find the way whose last use frequency cntr has the lowest value
      auto victim = std::min_element(begin, end);
      assert(begin <= victim);
      assert(victim < end);

      /*
      int _way_idx = 0;
      for (auto it = begin; it != end; ++it) {
        std::cout << "LFU: frequency counter for set " << set_idx << " at way " << _way_idx << ": " << *it << std::endl;
        _way_idx++;
      }
      */

      uint32_t victim_idx = static_cast<uint32_t>(std::distance(begin, victim)); // cast protected by prior asserts
	    //std::cout << "LFU:victim:" << victim_idx << std::endl;
	    return victim_idx;
    }
};
/************************************************************************/

/*************
 * TXVC Prefetcher interface
 *************/
class PrefetchPolicy
{
  public:
    virtual ~PrefetchPolicy() = default;

    // Return zero or more prefetch candidate byte-addresses for the given access.
    // Inner vector ordering: highest priority first. Empty vector means no prefetch.
    // translation_level: ChampSim PTW level (1=PTE leaf, 4=PGD root; 0=non-PTE).
    // ip: walker instruction pointer.
    virtual std::vector<uint64_t> get_prefetch_candidates(uint64_t address, std::size_t translation_level, uint64_t ip) = 0;

    // Fraction (0-100) of the MSHR that must be free before a prefetch is issued.
    virtual uint32_t get_mshr_gate_pct() const = 0;

    // Feedback from the cache: called when a prefetch was useful (demand hit) or useless (evicted).
    virtual void notify_useful()  {}
    virtual void notify_useless() {}
};

class NonePrefetcher : public PrefetchPolicy
{
  public:
    NonePrefetcher()
    {
      std::cout << "TXVC PrefetchPolicy: none" << std::endl;
    }

    std::vector<uint64_t> get_prefetch_candidates(uint64_t, std::size_t, uint64_t) override
    {
      return {}; // prefetching disabled
    }

    uint32_t get_mshr_gate_pct() const override
    {
      return 100; // put anything here, doesn't matter since prefetching is disableds
    }
};

/*************
 * TXVC Stride Prefetcher
 *
 * Env vars:
 *   TXVC_PF_STRIDE_TABLE_SIZE       - number of predictor entries (default 256)
 *   TXVC_PF_STRIDE_CONF_THRESHOLD   - minimum confidence (0-3) to issue a prefetch (default 2)
 *   TXVC_PF_MSHR_GATE_PCT    - issue only when MSHR occupancy < size * pct / 100 (default 50)
 *************/
class StridePrefetcher : public PrefetchPolicy
{
  private:
    struct Entry {
      uint64_t last_cl_addr = 0;
      int64_t  last_delta   = 0;
      uint8_t  confidence   = 0;
      bool     valid        = false;
    };

    std::size_t table_size;
    uint8_t     conf_threshold;
    uint32_t    mshr_gate_pct;
    uint64_t    offset_bits;
    std::vector<Entry> table;

  public:
    StridePrefetcher(uint64_t _offset_bits) : offset_bits(_offset_bits)
    {
      // table size
      if (const char* e = getenv("TXVC_PF_STRIDE_TABLE_SIZE")) {
        std::size_t v = static_cast<std::size_t>(std::stoull(e));
        table_size = (v >= 1) ? v : 256;
        if (v < 1)
          std::cerr << "TXVC_PF_STRIDE_TABLE_SIZE must be >= 1, using default 256" << std::endl;
      } else {
        table_size = 256;
      }

      // confidence threshold
      if (const char* e = getenv("TXVC_PF_STRIDE_CONF_THRESHOLD")) {
        int v = std::stoi(e);
        if (v < 0 || v > 3) {
          std::cerr << "TXVC_PF_STRIDE_CONF_THRESHOLD must be 0-3, using default 2" << std::endl;
          v = 2;
        }
        conf_threshold = static_cast<uint8_t>(v);
      } else {
        conf_threshold = 2;
      }

      // MSHR gate percentage
      if (const char* e = getenv("TXVC_PF_MSHR_GATE_PCT")) {
        int v = std::stoi(e);
        if (v <= 0 || v > 100) {
          std::cerr << "TXVC_PF_MSHR_GATE_PCT must be 1-100, using default 50" << std::endl;
          v = 50;
        }
        mshr_gate_pct = static_cast<uint32_t>(v);
      } else {
        mshr_gate_pct = 50;
      }

      table.resize(table_size);

      std::cout << "TXVC StridePrefetcher: table_size=" << table_size
                << " conf_threshold=" << static_cast<int>(conf_threshold)
                << " mshr_gate_pct=" << mshr_gate_pct << std::endl;
    }

    uint32_t get_mshr_gate_pct() const override { return mshr_gate_pct; }

    std::vector<uint64_t> get_prefetch_candidates(uint64_t address, std::size_t /*translation_level*/, uint64_t /*ip*/) override
    {
      const uint64_t cl_addr = address >> offset_bits;
      auto& pred = table[cl_addr % table_size];
      std::vector<uint64_t> candidates;

      if (pred.valid && pred.confidence >= conf_threshold) {
        const int64_t next_cl = static_cast<int64_t>(cl_addr) + pred.last_delta;
        if (next_cl >= 0 && next_cl <= static_cast<int64_t>(std::numeric_limits<uint64_t>::max() >> offset_bits))
          candidates.push_back(static_cast<uint64_t>(next_cl) << offset_bits);
      }

      if (pred.valid) {
        const int64_t delta = static_cast<int64_t>(cl_addr) - static_cast<int64_t>(pred.last_cl_addr);
        if (delta == pred.last_delta) {
          if (pred.confidence < 3) pred.confidence++;
        } else {
          pred.last_delta = delta;
          pred.confidence = 0;
        }
      } else {
        pred.valid      = true;
        pred.last_delta = 0;
        pred.confidence = 0;
      }

      pred.last_cl_addr = cl_addr;
      return candidates;
    }
};

/*************
 * TXVC Sibling Prefetcher
 *
 * Exploits page-table tree structure: adjacent virtual pages tend to access
 * PTEs that share the same 4KB page-table page (siblings in the PT tree).
 * The predictor tracks the stride between successive accesses *within* the
 * same PT page and prefetches the next cache line in that page, guaranteeing
 * it never crosses the page-table-page boundary.
 *
 * Usefulness controller: rolling accuracy window (bitset, max 64 entries)
 * auto-throttles degree to 0 when accuracy drops below acc_threshold %.
 * Re-enables as soon as accuracy recovers above the threshold.
 *
 * Env vars:
 *   TXVC_PF_SBLG_TABLE_SIZE     - predictor entries (default 128)
 *   TXVC_PF_SBLG_CONF_THRESHOLD - min confidence 0-3 to issue (default 2)
 *   TXVC_PF_SBLG_ACC_WINDOW     - rolling window size, 4-64 (default 32)
 *   TXVC_PF_SBLG_ACC_THRESHOLD  - min % accuracy to stay enabled (default 20)
 *   TXVC_PF_MSHR_GATE_PCT       - shared with stride prefetcher (default 50)
 *************/
class SiblingPrefetcher : public PrefetchPolicy
{
  private:
    struct Entry {
      uint64_t page_tag    = 0;
      int16_t  last_cl_off = 0;
      int16_t  last_delta  = 0;
      uint8_t  confidence  = 0;
      bool     valid       = false;
    };

    struct UsefulnessController {
      uint64_t bits       = 0;
      uint32_t pos        = 0;
      uint32_t useful_cnt = 0;
      uint32_t filled     = 0;
      uint32_t window_sz;
      uint32_t threshold;
      bool     enabled    = true;

      UsefulnessController() : window_sz(32), threshold(20) {}
      UsefulnessController(uint32_t w, uint32_t t) : window_sz(w), threshold(t) {}

      void push(bool useful) {
        const uint32_t idx = pos % window_sz;
        const bool evicted = (bits >> idx) & 1ULL;
        if (evicted) useful_cnt--;
        if (useful) {
          bits |= (1ULL << idx);
          useful_cnt++;
        } else {
          bits &= ~(1ULL << idx);
        }
        pos = (pos + 1) % window_sz;
        if (filled < window_sz) filled++;
        // Only update the enable flag once we have filled at least half the window
        if (filled >= window_sz / 2) {
          enabled = (useful_cnt * 100 / filled >= threshold);
        }
      }

      bool is_enabled() const { return enabled; }
    };

    std::size_t          table_size;
    uint8_t              conf_threshold;
    uint32_t             mshr_gate_pct;
    uint64_t             offset_bits;
    uint64_t             cls_per_page;
    uint64_t             cls_per_page_bits;
    std::vector<Entry>   table;
    UsefulnessController uc;
    uint32_t             degree;

  public:
    SiblingPrefetcher(uint64_t _offset_bits) : offset_bits(_offset_bits)
    {
      // 4KB page-table page, derive number of CLs per page
      const uint64_t page_bits = 12;
      cls_per_page = (1ULL << page_bits) >> offset_bits;  // 64 for 64B CLs
      cls_per_page_bits = 0;
      for (uint64_t tmp = cls_per_page >> 1; tmp; tmp >>= 1) cls_per_page_bits++;

      // table size
      if (const char* e = getenv("TXVC_PF_SBLG_TABLE_SIZE")) {
        std::size_t v = static_cast<std::size_t>(std::stoull(e));
        table_size = (v >= 1) ? v : 128;
        if (v < 1)
          std::cerr << "TXVC_PF_SBLG_TABLE_SIZE must be >= 1, using default 128" << std::endl;
      } else {
        table_size = 128;
      }

      // confidence threshold
      if (const char* e = getenv("TXVC_PF_SBLG_CONF_THRESHOLD")) {
        int v = std::stoi(e);
        if (v < 0 || v > 3) {
          std::cerr << "TXVC_PF_SBLG_CONF_THRESHOLD must be 0-3, using default 2" << std::endl;
          v = 2;
        }
        conf_threshold = static_cast<uint8_t>(v);
      } else {
        conf_threshold = 2;
      }

      // MSHR gate percentage
      if (const char* e = getenv("TXVC_PF_MSHR_GATE_PCT")) {
        int v = std::stoi(e);
        if (v <= 0 || v > 100) {
          std::cerr << "TXVC_PF_MSHR_GATE_PCT must be 1-100, using default 50" << std::endl;
          v = 50;
        }
        mshr_gate_pct = static_cast<uint32_t>(v);
      } else {
        mshr_gate_pct = 50;
      }

      // Usefulness window
      uint32_t acc_window = 32;
      if (const char* e = getenv("TXVC_PF_SBLG_ACC_WINDOW")) {
        int v = std::stoi(e);
        if (v >= 4 && v <= 64)
          acc_window = static_cast<uint32_t>(v);
        else
          std::cerr << "TXVC_PF_SBLG_ACC_WINDOW must be 4-64, using default 32" << std::endl;
      }
      uint32_t acc_threshold = 20;
      if (const char* e = getenv("TXVC_PF_SBLG_ACC_THRESHOLD")) {
        int v = std::stoi(e);
        if (v >= 0 && v <= 100)
          acc_threshold = static_cast<uint32_t>(v);
        else
          std::cerr << "TXVC_PF_SBLG_ACC_THRESHOLD must be 0-100, using default 20" << std::endl;
      }

      uc = UsefulnessController(acc_window, acc_threshold);

      // Prefetch degree (max candidates per access)
      degree = 1;
      if (const char* e = getenv("TXVC_PF_SBLG_DEGREE")) {
        int v = std::stoi(e);
        if (v >= 1 && v <= 8)
          degree = static_cast<uint32_t>(v);
        else
          std::cerr << "TXVC_PF_SBLG_DEGREE must be 1-8, using default 1" << std::endl;
      }

      table.resize(table_size);

      std::cout << "TXVC SiblingPrefetcher: table_size=" << table_size
                << " conf_threshold=" << static_cast<int>(conf_threshold)
                << " mshr_gate_pct=" << mshr_gate_pct
                << " cls_per_page=" << cls_per_page
                << " acc_window=" << acc_window
                << " acc_threshold=" << acc_threshold
                << " degree=" << degree << std::endl;
    }

    uint32_t get_mshr_gate_pct() const override { return mshr_gate_pct; }

    void notify_useful()  override { uc.push(true);  }
    void notify_useless() override { uc.push(false); }

    std::vector<uint64_t> get_prefetch_candidates(uint64_t address, std::size_t /*translation_level*/, uint64_t /*ip*/) override
    {
      if (!uc.is_enabled()) return {};

      const uint64_t cl_addr  = address >> offset_bits;
      const uint64_t page_tag = cl_addr >> cls_per_page_bits;
      const int16_t  cl_off   = static_cast<int16_t>(cl_addr & (cls_per_page - 1));
      auto& pred = table[page_tag % table_size];
      std::vector<uint64_t> candidates;

      // Emit up to `degree` candidates before updating the predictor state.
      // Each candidate is cl_off + k*delta for k = 1..degree, clamped to the
      // PT page boundary so we never reference a different page-table page.
      if (pred.valid && pred.page_tag == page_tag && pred.confidence >= conf_threshold) {
        for (uint32_t k = 1; k <= degree; ++k) {
          const int16_t next_off = static_cast<int16_t>(cl_off + static_cast<int16_t>(k) * pred.last_delta);
          if (next_off < 0 || next_off >= static_cast<int16_t>(cls_per_page))
            break; // stop at boundary, don't skip and continue
          candidates.push_back(((page_tag << cls_per_page_bits) | static_cast<uint64_t>(next_off)) << offset_bits);
        }
      }

      // Update entry
      if (pred.valid && pred.page_tag == page_tag) {
        const int16_t delta = cl_off - pred.last_cl_off;
        if (delta == pred.last_delta) {
          if (pred.confidence < 3) pred.confidence++;
        } else {
          pred.last_delta = delta;
          pred.confidence = 0;
        }
      } else {
        // Different page_tag evicts the old entry
        pred.page_tag   = page_tag;
        pred.last_delta = 0;
        pred.confidence = 0;
      }

      pred.valid       = true;
      pred.last_cl_off = cl_off;
      return candidates;
    }
};

/*************
 * TXVC Child Prefetcher
 *
 * Exploits the parent→child relationship in the page table walk chain.
 * When the PTW misses at level L (a parent node), this predictor looks up a
 * learned (IP, parent_cl_addr) → child_cl_addr mapping and prefetches the
 * expected level L-1 entry before the parent miss has even returned.
 *
 * Training: every miss at level L is paired with the most recently seen miss
 * at level L+1 from the same IP.  That (parent, child) pair trains the table.
 *
 * Prediction: on a miss at any level > 1, look up (IP, current_cl_addr) and
 * return the predicted child cl address if confidence is sufficient.
 *
 * Env vars:
 *   TXVC_PF_CHILD_TABLE_SIZE     - prediction table entries (default 256)
 *   TXVC_PF_CHILD_PENDING_SIZE   - pending-parent table entries (default 64)
 *   TXVC_PF_CHILD_CONF_THRESHOLD - min confidence 0-3 to issue (default 2)
 *   TXVC_PF_MSHR_GATE_PCT        - shared with other prefetchers (default 50)
 *************/
class ChildPrefetcher : public PrefetchPolicy
{
  private:
    struct PredEntry {
      uint64_t ip             = 0;
      uint64_t parent_cl_addr = 0;
      uint64_t child_cl_addr  = 0;
      uint8_t  confidence     = 0;
      bool     valid          = false;
    };

    // Records the most recent miss at a given level for a given IP.
    struct PendingParent {
      uint64_t   ip      = 0;
      uint64_t   cl_addr = 0;
      std::size_t level  = 0;
      bool       valid   = false;
    };

    std::size_t              table_size;
    std::size_t              pending_size;
    uint8_t                  conf_threshold;
    uint32_t                 mshr_gate_pct;
    uint64_t                 offset_bits;
    std::vector<PredEntry>   table;
    std::vector<PendingParent> pending; // indexed by ip % pending_size

    std::size_t pred_index(uint64_t ip, uint64_t parent_cl_addr) const
    {
      // Mix IP and parent address bits to reduce aliasing
      return (ip ^ (parent_cl_addr * 2654435761ULL)) % table_size;
    }

  public:
    ChildPrefetcher(uint64_t _offset_bits) : offset_bits(_offset_bits)
    {
      if (const char* e = getenv("TXVC_PF_CHILD_TABLE_SIZE")) {
        std::size_t v = static_cast<std::size_t>(std::stoull(e));
        table_size = (v >= 1) ? v : 256;
        if (v < 1) std::cerr << "TXVC_PF_CHILD_TABLE_SIZE must be >= 1, using 256" << std::endl;
      } else {
        table_size = 256;
      }

      if (const char* e = getenv("TXVC_PF_CHILD_PENDING_SIZE")) {
        std::size_t v = static_cast<std::size_t>(std::stoull(e));
        pending_size = (v >= 1) ? v : 64;
        if (v < 1) std::cerr << "TXVC_PF_CHILD_PENDING_SIZE must be >= 1, using 64" << std::endl;
      } else {
        pending_size = 64;
      }

      if (const char* e = getenv("TXVC_PF_CHILD_CONF_THRESHOLD")) {
        int v = std::stoi(e);
        if (v < 0 || v > 3) {
          std::cerr << "TXVC_PF_CHILD_CONF_THRESHOLD must be 0-3, using default 2" << std::endl;
          v = 2;
        }
        conf_threshold = static_cast<uint8_t>(v);
      } else {
        conf_threshold = 2;
      }

      if (const char* e = getenv("TXVC_PF_MSHR_GATE_PCT")) {
        int v = std::stoi(e);
        mshr_gate_pct = (v > 0 && v <= 100) ? static_cast<uint32_t>(v) : 50u;
      } else {
        mshr_gate_pct = 50;
      }

      table.resize(table_size);
      pending.resize(pending_size);

      std::cout << "TXVC ChildPrefetcher: table_size=" << table_size
                << " pending_size=" << pending_size
                << " conf_threshold=" << static_cast<int>(conf_threshold)
                << " mshr_gate_pct=" << mshr_gate_pct << std::endl;
    }

    uint32_t get_mshr_gate_pct() const override { return mshr_gate_pct; }

    std::vector<uint64_t> get_prefetch_candidates(uint64_t address, std::size_t translation_level, uint64_t ip) override
    {
      // Only operates on PTE-path accesses (level > 0)
      if (translation_level == 0) return {};

      const uint64_t cl_addr = address >> offset_bits;
      std::vector<uint64_t> candidates;

      // --- Training ---
      // Check if there is a pending parent at level+1 for this IP.
      // If so, this access (cl_addr at level L) is the child of that parent.
      PendingParent& pp = pending[ip % pending_size];
      if (pp.valid && pp.ip == ip && pp.level == translation_level + 1) {
        const std::size_t idx = pred_index(ip, pp.cl_addr);
        PredEntry& entry = table[idx];
        if (entry.valid && entry.ip == ip && entry.parent_cl_addr == pp.cl_addr) {
          // Entry exists for this (IP, parent): update confidence
          if (entry.child_cl_addr == cl_addr) {
            if (entry.confidence < 3) entry.confidence++;
          } else {
            // New child observed for same parent — reset
            entry.child_cl_addr = cl_addr;
            entry.confidence    = 0;
          }
        } else {
          // Allocate fresh entry
          entry.valid          = true;
          entry.ip             = ip;
          entry.parent_cl_addr = pp.cl_addr;
          entry.child_cl_addr  = cl_addr;
          entry.confidence     = 0;
        }
      }

      // Update pending parent: record this miss as the new "last seen at level L" for this IP
      pp.valid   = true;
      pp.ip      = ip;
      pp.cl_addr = cl_addr;
      pp.level   = translation_level;

      // --- Prediction ---
      // Only prefetch if this is not a leaf (level > 1): there is a child level below.
      if (translation_level > 1) {
        const std::size_t idx = pred_index(ip, cl_addr);
        const PredEntry& entry = table[idx];
        if (entry.valid && entry.ip == ip && entry.parent_cl_addr == cl_addr
            && entry.confidence >= conf_threshold)
          candidates.push_back(entry.child_cl_addr << offset_bits);
      }

      return candidates;
    }
};

/*************
 * TXVC Combined (Stride + Sibling) Prefetcher
 *
 * Priority order: child (cross-level) → sibling (within PT page) → stride (fallback).
 * Child fires on upper-level misses (level > 1), sibling on any level.
 * Useful/useless feedback is forwarded to sibling (which has a usefulness controller);
 * child and stride don't need it as they have confidence-gating instead.
 *************/
class CombinedPrefetcher : public PrefetchPolicy
{
  private:
    StridePrefetcher  stride_pf;
    SiblingPrefetcher sibling_pf;
    ChildPrefetcher   child_pf;
    uint32_t          mshr_gate_pct;

  public:
    CombinedPrefetcher(uint64_t offset_bits)
      : stride_pf(offset_bits), sibling_pf(offset_bits), child_pf(offset_bits)
    {
      if (const char* e = getenv("TXVC_PF_MSHR_GATE_PCT")) {
        int v = std::stoi(e);
        mshr_gate_pct = (v > 0 && v <= 100) ? static_cast<uint32_t>(v) : 50u;
      } else {
        mshr_gate_pct = 50;
      }
      std::cout << "TXVC CombinedPrefetcher (child+sibling+stride): mshr_gate_pct=" << mshr_gate_pct << std::endl;
    }

    uint32_t get_mshr_gate_pct() const override { return mshr_gate_pct; }

    void notify_useful() override
    {
      stride_pf.notify_useful();
      sibling_pf.notify_useful();
    }

    void notify_useless() override
    {
      stride_pf.notify_useless();
      sibling_pf.notify_useless();
    }

    std::vector<uint64_t> get_prefetch_candidates(uint64_t address, std::size_t translation_level, uint64_t ip) override
    {
      // Child first: cross-level prefetch (parent→child), only fires for level > 1
      std::vector<uint64_t> child = child_pf.get_prefetch_candidates(address, translation_level, ip);
      if (!child.empty()) return child;
      // Sibling: within-PT-page stride, fires at any level
      std::vector<uint64_t> sblg = sibling_pf.get_prefetch_candidates(address, translation_level, ip);
      if (!sblg.empty()) return sblg;
      // Fall back to global stride predictor
      return stride_pf.get_prefetch_candidates(address, translation_level, ip);
    }
};

#endif