[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = pb_child_pf_size_impact
plot_type = ipc
file_type = png
group_size = 6
alternative_tags = BASELINE, L1-16KB, L1-32KB, L1-64KB, L1-128KB, L1-512KB, L1-Unlimited, L2-16KB, L2-32KB, L2-64KB, L2-128KB, L2-512KB, L2-Unlimited, LLC-16KB, LLC-32KB, LLC-64KB, LLC-128KB, LLC-512KB, LLC-Unlimited

[EXPERIMENT]
name = pb_child_pf_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_pb = pb-s${l1d.pf_buffer_sets}-w${l1d.pf_buffer_ways}-l1d_child_ideal_pf, pb-s${l2c.pf_buffer_sets}-w${l2c.pf_buffer_ways}-l2c_child_ideal_pf, pb-s${llc.pf_buffer_sets}-w${llc.pf_buffer_ways}-llc_child_ideal_pf
#, pb-llc_child_ideal_pf
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_pb)s
#simulations = pb-llc_child_ideal_pf

[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = next_line
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = ip_stride
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[pb-s${l1d.pf_buffer_sets}-w${l1d.pf_buffer_ways}-l1d_child_ideal_pf]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = pf_combiner 
l1d.pf_mshr_gate_pct = 95
l1d.pf_child_train_on_hit = 1
l1d.pf_child_issue_on_hit = 1
l1d.pf_child_fill_this_level = 1
l1d.enable_pf_buffer = 1
l1d.pf_buffer_sets = 16 32 64 128 512 4096
l1d.pf_buffer_ways = 16
l1d.pf_buffer_repl_policy = 1
ooo_cpu.enable_txvc = true
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = ip_stride
l2c.enable_pf_buffer = 0
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no
llc.enable_pf_buffer = 0

[pb-s${l2c.pf_buffer_sets}-w${l2c.pf_buffer_ways}-l2c_child_ideal_pf]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = pf_combiner 
l1d.pf_mshr_gate_pct = 95
l1d.pf_child_train_on_hit = 1
l1d.pf_child_issue_on_hit = 1
l1d.pf_child_fill_this_level = 0
l1d.enable_pf_buffer = 0
ooo_cpu.enable_txvc = true
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = ip_stride
l2c.enable_pf_buffer = 1
l2c.pf_buffer_sets =  16 32 64 128 512 4096
l2c.pf_buffer_ways = 16
l2c.pf_buffer_repl_policy = 1
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no
llc.enable_pf_buffer = 0

[pb-s${llc.pf_buffer_sets}-w${llc.pf_buffer_ways}-llc_child_ideal_pf]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = pf_combiner 
l1d.pf_mshr_gate_pct = 95
l1d.pf_child_train_on_hit = 1
l1d.pf_child_issue_on_hit = 1
l1d.pf_child_fill_this_level = 0
l1d.enable_pf_buffer = 0
ooo_cpu.enable_txvc = true
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = ip_stride
l2c.enable_pf_buffer = 0
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no
llc.enable_pf_buffer = 1
llc.pf_buffer_sets = 16 32 64 128 512 4096
llc.pf_buffer_ways = 16
llc.pf_buffer_repl_policy = 1