[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = pb_sibling_pf_eval
plot_type = ipc
file_type = png
#alternative_tags = BASELINE, PF_L1D-F_L1D, PF_L1D-F_L2C, PF_L1D-F_LLC

[EXPERIMENT]
name = pb_sibling_pf_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_pb = pb-l1d_sibling_pf, pb-l2c_sibling_pf
#, pb-llc_child_ideal_pf
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_pb)s
#simulations = pb-llc_child_ideal_pf

[BASELINE]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[pb-l1d_sibling_pf]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = tx_sibling
l1d.pf_mshr_gate_pct = 95
l1d.pf_sblg_conf_threshold = 2
l1d.pf_sblg_table_size = 65536
l1d.pf_sblg_acc_window = 32
l1d.pf_sblg_acc_threshold = 0
l1d.pf_sblg_degree = 1
l1d.enable_pf_buffer = 1
l1d.pf_buffer_sets = 65536
l1d.pf_buffer_ways = 1
ooo_cpu.enable_txvc = true
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
l2c.enable_pf_buffer = 0
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no
llc.enable_pf_buffer = 0

[pb-l2c_sibling_pf]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l1d.enable_pf_buffer = 0
ooo_cpu.enable_txvc = true
l2c.sets = 2048
l2c.ways = 8
l2c.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l2c.prefetcher = tx_sibling
l2c.pf_mshr_gate_pct = 75
l2c.pf_sblg_conf_threshold = 2
l2c.pf_sblg_table_size = 65536
l2c.pf_sblg_acc_window = 32
l2c.pf_sblg_acc_threshold = 0
l2c.pf_sblg_degree = 1
l2c.enable_pf_buffer = 1
l2c.pf_buffer_sets = 65536
l2c.pf_buffer_ways = 1
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no
llc.enable_pf_buffer = 0
