# TODO: add preprocessor to make conf files more versatile 
[BASE]
ROOT_DIR = ./
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 500000 # 50000000
run_instructions = 1000000 # 100000000
time = 00:00:30 #04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_test_ipc
plot_type = plot_ipc # TODO: plot multiple types
file_type = pdf
# TODO: add aliasing for tag names
# alternative_tags= ...Alternative names for sim, should match order and...
# TODO: some way we should manage and assign baselines

[EXPERIMENT]
name = test_base
workload = debug
simulations = BASELINE
#simulations = iTP+xPTP
debug_run = false
# TODO automate experiment generation
# component.parameter1 = x y z
# component.parameter2 = a b c
# tag_template = TXVC-${component.parameter1}-${component.parameter2}

[BASELINE]
# TODO: add functionality to reuse data from other folders
# optional, to avoid running this specific simulation, and allow only parsing(?), plotting
skip_simulation = false
# simulation_stats = /path/to/file
#simulation_stats = 
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16