# TODO: add preprocessor to make conf files more versatile 
[BASE]
ROOT_DIR = ./
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 500000 # 50000000
run_instructions = 1000000 # 100000000
time = 00:00:30 #04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_32KB
plot_type = plot_ipc 
# TODO: plot multiple types
file_type = pdf

# TODO: add aliasing for tag names
# alternative_tags= ...Alternative names for sim, should match order and...
# TODO: some way we should manage and assign baselines

[EXPERIMENT]
name = test
workload = debug
#simulations = BASELINE, TXVC-32KB, TXVC-32KB-DOA-OLD, TXVC-32KB-DOA-CNTR_SZ-1, TXVC-32KB-DOA-CNTR_SZ-2, TXVC-32KB-DOA-CNTR_SZ-3, TXVC-32KB-DOA-CNTR_SZ-4, TXVC-32KB-DOA-CNTR_SZ-5
simulations = BeladyOPTSet
debug_run = true
parallel_run = true
# TODO automate experiment generation
# component.parameter1 = x y z
# component.parameter2 = a b c
# tag_template = TXVC-${component.parameter1}-${component.parameter2}

[BASELINE]
# TODO: add functionality to reuse data from other folders
# optional, to avoid running this specific simulation, and allow only parsing(?), plotting
skip_simulation = false
# simulation_stats = /path/to/file
#simulation_stats = 
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[TXVC-4KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = false


[TXVC-4KB-DOA-CNTR_SZ-1]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 1


[TXVC-4KB-DOA-CNTR_SZ-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 2
txvc.dbpred_use_bias = false

[TXVC-4KB-DOA-CNTR_SZ-2-BIAS]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data
txvc.filter_frequency_threshold = 500
#txvc.dbpred_cntr_size = 2
#txvc.dbpred_use_bias = true

[TXVC-4K-DOA-CNTR_SZ-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 3


[TXVC-4K-DOA-CNTR_SZ-4]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 4


[TXVC-4KB-DOA-CNTR_SZ-5]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 5

[TXVC-4KB-MFU]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = mfu

[TXVC-32KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = false

[TXVC-32KB-DOA-OLD]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa-simple

[TXVC-32KB-DOA-CNTR_SZ-1]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 1

[TXVC-32KB-DOA-CNTR_SZ-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 2

[TXVC-32KB-DOA-CNTR_SZ-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 3

[TXVC-32KB-DOA-CNTR_SZ-4]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 4


[TXVC-32KB-DOA-CNTR_SZ-5]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 5

[BeladyOPTSet]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 1024 
#l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.ways = 512 
#txvc.ways = 1024 
#txvc.ways = 2048 
txvc.ways = 4096
#txvc.ways = 512 1024 2048 4096
txvc.cache_filtering = true
txvc.cache_filter = beladyOPT-set
#txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.filter_size = 1024
txvc.filter_num_hashes = 3
#txvc.replacement = lru
txvc.replacement = lfu