[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = tx_buffer_perfect_no_cache_fill
plot_type = ipc
file_type = png
#alternative_tags = BASELINE, SBLG-PF, CHILD-PF


[EXPERIMENT]
name = tx_buffer_perfect_no_cache_fill
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_bf = bf_l1d, bf_l2c, bf_llc
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_bf)s

[BASELINE]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[bf_l1d]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.enable_pf_buffer = 1
l1d.pf_buffer_mode = MISS
l1d.pf_buffer_fill_cache_on_hit = 0
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[bf_l2c]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.enable_pf_buffer = 1
l2c.pf_buffer_mode = MISS
l2c.pf_buffer_fill_cache_on_hit = 0
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[bf_llc]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.enable_pf_buffer = 1
llc.pf_buffer_mode = MISS
llc.pf_buffer_fill_cache_on_hit = 0
