[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = tx_child_pf_unlimited
plot_type = ipc
file_type = png
#alternative_tags = BASELINE, SBLG-PF, CHILD-PF


[EXPERIMENT]
name = tx_prefetch_eval_unlimited
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_child_ideal_pf = child_ideal_pf_gate-${l1d.pf_mshr_gate_pct}_ih-${l1d.pf_child_issue_on_hit}_l1d, child_ideal_pf_gate-${l2c.pf_mshr_gate_pct}_ih-${l2c.pf_child_issue_on_hit}_l2c, child_ideal_pf_gate-${llc.pf_mshr_gate_pct}_ih-${llc.pf_child_issue_on_hit}_llc
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_child_ideal_pf)s

[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[child_ideal_pf_gate-${l1d.pf_mshr_gate_pct}_ih-${l1d.pf_child_issue_on_hit}_l1d]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = child_ideal
l1d.pf_mshr_gate_pct = 0 25 50 75
l1d.pf_child_train_on_hit = 1 
l1d.pf_child_issue_on_hit = 0 1 
l1d.enable_pf_buffer = 1
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[child_ideal_pf_gate-${l2c.pf_mshr_gate_pct}_ih-${l2c.pf_child_issue_on_hit}_l2c]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l2c.prefetcher = child_ideal
l2c.pf_mshr_gate_pct = 0 25 50 75
l2c.pf_child_train_on_hit = 1
l2c.pf_child_issue_on_hit = 0 1
l2c.enable_pf_buffer = 1
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[child_ideal_pf_gate-${llc.pf_mshr_gate_pct}_ih-${llc.pf_child_issue_on_hit}_llc]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetch_activate = LOAD,PREFETCH,TRANSLATION
llc.prefetcher = child_ideal
llc.pf_mshr_gate_pct = 0 25 50 75
llc.pf_child_train_on_hit = 1
llc.pf_child_issue_on_hit = 0 1
llc.enable_pf_buffer = 1
