[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = tx_prefetch_eval_unlimited
plot_type = ipc
file_type = png
#alternative_tags = BASELINE, SBLG-PF, CHILD-PF


[EXPERIMENT]
name = tx_prefetch_eval_unlimited
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_sblg_pf = sblgpf_l1d, sblgpf_l2c, sblgpf_llc
simulations_child_pf = childpf_l1d, childpf_l2c, childpf_llc
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_sblg_pf)s, %(simulations_child_pf)s

[BASELINE]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16

[sblgpf_l1d]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = tx_sibling
l1d.pf_mshr_gate_pct = 75
l1d.pf_sblg_conf_threshold = 1
l1d.pf_sblg_table_size = 65536
l1d.pf_sblg_acc_window = 32
l1d.pf_sblg_acc_threshold = 0
l1d.pf_sblg_degree = 1
l1d.pf_buffer.cache = L1D
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[sblgpf_l2c]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
l2c.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l2c.prefetcher = tx_sibling
l2c.pf_mshr_gate_pct = 75
l2c.pf_sblg_conf_threshold = 1
l2c.pf_sblg_table_size = 65536
l2c.pf_sblg_acc_window = 32
l2c.pf_sblg_acc_threshold = 0
l2c.pf_sblg_degree = 1
l2c.pf_buffer.cache = L2C
llc.sets = 1024
llc.ways = 16

[sblgpf_l2c]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
llc.prefetch_activate = LOAD,PREFETCH,TRANSLATION
llc.prefetcher = tx_sibling
llc.pf_mshr_gate_pct = 75
llc.pf_sblg_conf_threshold = 1
llc.pf_sblg_table_size = 65536
llc.pf_sblg_acc_window = 32
llc.pf_sblg_acc_threshold = 0
llc.pf_sblg_degree = 1
llc.pf_buffer.cache = LLC

[childpf_l1d]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = tx_child
l1d.pf_mshr_gate_pct = 75
l1d.pf_child_conf_threshold = 1
l1d.pf_child_table_size = 65536
l1d.pf_child_pending_size = 65536
l1d.pf_child_train_on_hit = 1
l1d.pf_child_issue_on_hit = 1
l1d.pf_buffer.cache = L1D
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[childpf_l2c]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
l2c.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l2c.prefetcher = tx_child
l2c.pf_mshr_gate_pct = 75
l2c.pf_child_conf_threshold = 1
l2c.pf_child_table_size = 65536
l2c.pf_child_pending_size = 65536
l2c.pf_child_train_on_hit = 1
l2c.pf_child_issue_on_hit = 1
l2c.pf_buffer.cache = L2C
llc.sets = 1024
llc.ways = 16

[childpf_llc]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
llc.prefetch_activate = LOAD,PREFETCH,TRANSLATION
llc.prefetcher = tx_child
llc.pf_mshr_gate_pct = 75
llc.pf_child_conf_threshold = 1
llc.pf_child_table_size = 65536
llc.pf_child_pending_size = 65536
llc.pf_child_train_on_hit = 1
llc.pf_child_issue_on_hit = 1
llc.pf_buffer.cache = LLC