[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_txvc_no_prefetch_base
plot_type = plot_ipc
file_type = pdf

[EXPERIMENT]
name = txvc_no_prefetch_base
workload = selected_qualcomm_srv_ap
#workload = smt_qualcomm_srv_ap
debug_run = false
parallel_run = false
simulations = BASELINE, TXVC-4KB, TXVC-4KB_DOA-NAIVE, TXVC-4KB_DOA
#simulations = iTP, iTP+xPTP, <%(simulations_txvc)s, %(simulations_dtxvc)s
#simulations = %(simulations_dtxvc)s

[BASELINE]
l1i.prefetcher = no
l1d.prefetcher = no
l2c.prefetcher = no
llc.sets = 1537
llc.ways = 16

[TXVC-4KB]
l1i.prefetcher = no
l1d.prefetcher = no
l2c.prefetcher = no
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = false

[TXVC-4KB_DOA-NAIVE]
l1i.prefetcher = no
l1d.prefetcher = no
l2c.prefetcher = no
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = doa-simple

[TXVC-4KB_DOA]
l1i.prefetcher = no
l1d.prefetcher = no
l2c.prefetcher = no
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 3