[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
#plot_name = access_freq_analysis
plot_name = access_freq_range_analysis5
plot_type = plot_ipc
file_type = pdf
#alternative_tags = BASELINE, >=2, >=5,>=10, >=40, >=60, >=80, >=100, >=200, >=300, >=400, >=500
#alternative_tags = BASELINE, <=2, <=5, <=10, <=40, <=60, <=80, <=100, <=200, <=300, <=400, <=500
range1_tags = BASELINE, [1-2), [2-5), [5-10), [10-40), [40-60), [60-80), [80-100), [100-200), [200-300), [300-400), [400-500), [500-Inf)
range2_tags = BASELINE, [1-100), [100-500), [500-Inf)
range3_tags = BASELINE, [2-5), [2-10), [2-40), [2-60), [2-80), [2-100), [2-200), [2-300), [2-400), [2-500), [2-Inf)
range4_tags = BASELINE, [2-500), [5-500), [10-500), [40-500), [60-500), [80-500), [100-500), [200-500), [300-500), [400-500)
alternative_tags = BASELINE, [2-Inf), [5-Inf), [10-Inf), [40-Inf), [60-Inf), [80-Inf), [100-Inf), [200-Inf), [300-Inf), [400-Inf), [500-Inf)
range6_tags = BASELINE, [10-Inf), [40-Inf)
#altenrative_tags = %(range5_tags)s

[EXPERIMENT]
#name = access_freq_analysis_l1
#name = access_freq_analysis_l2
#name = access_freq_analysis_l3
# for these we need to modify the mfu filter condition to the reverse one
#name = access_rev_freq_analysis_l1
#name = access_rev_freq_analysis_l2
#name = access_rev_freq_analysis_l3
# for these we only allow the ones that are equal to x freq (need to change source code)
#name = access_eq_freq_analysis_l1
# these do ranges
#name = access_freq_range_analysis_l1
name = access_freq_range_analysis_l2
#name = access_freq_range_analysis_l3
#name = test
# testing why performance is so low compared to unfiltered
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = debug
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_4KB_base = TXVC-4KB
simulations_4KB_freq = TXVC-4KB_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_32KB_base = TXVC-32KB
simulations_32KB_freq = TXVC-32KB_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_Inf_base = TXVC-Inf
simulations_Inf_l1d_freq = TXVC-Inf-L1D_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_Inf_l2c_freq = TXVC-Inf-L2C_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_Inf_llc_freq = TXVC-Inf-LLC_MFU-FREQ-${txvc.filter_frequency_threshold}
#simulations = BASELINE, TXVC-SETS-1-WAYS-${txvc.ways}
#simulations = BASELINE, TXVC-SETS-${txvc.sets}-WAYS-8
#simulations = BASELINE, %(simulations_Inf_l1d_freq)s
simulations = BASELINE, %(simulations_Inf_l2c_freq)s
#simulations = BASELINE, %(simulations_Inf_llc_freq)s
#simulations = BASELINE, %(simulations_32KB_freq)s, %(simulations_4KB_freq)s

[BASELINE]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
#simulation_stats = ./stats/txvc_cache_eval/BASELINE/google_srv_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[TXVC-4KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = false

[TXVC-4KB_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces
txvc.filter_frequency_threshold = 2 3 

[TXVC-32KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = false

[TXVC-32KB_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces
txvc.filter_frequency_threshold = 2 3

[TXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 32768
txvc.cache_filtering = false

[TXVC-Inf-L1D_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 1
txvc.sets = 1
txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces
#txvc.filter_frequency_threshold = 2 5 10 40 60 80 100 200 300 400 500
txvc.filter_frequency_threshold = 1-2 2-5 5-10 10-40 40-60 60-80 80-100 100-200 200-300 300-400 400-500
#txvc.filter_frequency_threshold = 1-100 100-500 500-999999
#this is for rev freq analysis
#txvc.filter_frequency_threshold = 2 3

[TXVC-Inf-L2C_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
#txvc.filter_frequency_threshold = 2 5 10 40 60 80 100 200 300 400 500
#txvc.filter_frequency_threshold = 1-2 2-5 5-10 10-40 40-60 60-80 80-100 100-200 200-300 300-400 400-500 500-999999
#txvc.filter_frequency_threshold = 1-100 100-500 500-999999
#txvc.filter_frequency_threshold = 2-5 2-10 2-40 2-60 2-80 2-100 2-200 2-300 2-400 2-500 2-999999
#txvc.filter_frequency_threshold = 2-500 5-500 10-500 40-500 60-500 80-400 100-500 200-500 300-500 400-500
txvc.filter_frequency_threshold = 2-999999 5-999999 10-999999 40-999999 60-999999 80-999999 100-999999 200-999999 300-999999 400-999999 500-999999
#this is for rev freq analysis
#txvc.filter_frequency_threshold = 2 5 10 100

[TXVC-Inf-LLC_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 3
txvc.sets = 1
txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_llc_traces
#txvc.filter_frequency_threshold = 2 5 10 40 60 80 100 200 300 400 500
txvc.filter_frequency_threshold = 1-2 2-5 5-10 10-40 40-60 60-80 80-100 100-200 200-300 300-400 400-500 500-999999
#txvc.filter_frequency_threshold = 1-100 100-500 500-999999
#this is for rev freq analysis
#txvc.filter_frequency_threshold = 2 5 10 100


