[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_prefetch_param_sweep
plot_type = ipc
file_type = png

[EXPERIMENT]
name = txvc_prefetch_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_txvc_64KB = TXVC_64KB_pf-${txvc.pf_policy}, TXVC_64KB_pf-${txvc.pf_policy}_thld-${txvc.pf_conf_threshold}_gate-${txvc.pf_mshr_gate_pct}_tblsize-${txvc.pf_table_size}
simulations_txvc_128KB = TXVC_128KB_pf-${txvc.pf_policy}, TXVC_128KB_pf-${txvc.pf_policy}_thld-${txvc.pf_conf_threshold}_gate-${txvc.pf_mshr_gate_pct}_tblsize-${txvc.pf_table_size}
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc_64KB)s
#, %(simulations_txvc_128KB)s


[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16


[TXVC_64KB_pf-${txvc.pf_policy}]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
txvc.pf_policy = none


[TXVC_64KB_pf-${txvc.pf_policy}_thld-${txvc.pf_conf_threshold}_gate-${txvc.pf_mshr_gate_pct}_tblsize-${txvc.pf_table_size}]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
txvc.pf_policy = stride
txvc.pf_conf_threshold = 1 2 3
txvc.pf_mshr_gate_pct = 25 40 50 60 75
txvc.pf_table_size = 256


[TXVC_128KB_pf-${txvc.pf_policy}]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
txvc.pf_policy = none


[TXVC_128KB_pf-${txvc.pf_policy}_thld-${txvc.pf_conf_threshold}_gate-${txvc.pf_mshr_gate_pct}_tblsize-${txvc.pf_table_size}]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
txvc.pf_policy = stride
txvc.pf_conf_threshold = 1 2 3
txvc.pf_mshr_gate_pct = 25 40 50 60 75
txvc.pf_table_size = 256