[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_child_prefetch_vc_size_eval
plot_type = ipc
file_type = png
#alternative_tags = BASELINE, child_ideal_pf_l1d


[EXPERIMENT]
name = txvc_prefetch_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_txvc = txvc-s${txvc.sets}-w${txvc.ways}-l${txvc.level}_child_ideal_pf, txvc-s${txvc.sets}-w${txvc.ways}-l${txvc.level}_freq_filter, txvc-s${txvc.sets}-w${txvc.ways}-l${txvc.level}_child_ideal_pf+freq_filter
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc)s

[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no


[txvc-s${txvc.sets}-w${txvc.ways}-l${txvc.level}_child_ideal_pf]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = child_ideal
l1d.pf_mshr_gate_pct = 95
l1d.pf_child_train_on_hit = 1
l1d.pf_child_issue_on_hit = 1
l1d.pf_child_populate_vc = 1
l1d.enable_pf_buffer = 0
ooo_cpu.enable_txvc = true
txvc.level = 1 2
txvc.sets = 32 64 128 256 65536
txvc.ways = 16
txvc.cache_filtering = false
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no


[txvc-s${txvc.sets}-w${txvc.ways}-l${txvc.level}_freq_filter]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetcher = no
ooo_cpu.enable_txvc = true
txvc.level = 1 2
txvc.sets = 32 64 128 256 65536
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no

[txvc-s${txvc.sets}-w${txvc.ways}-l${txvc.level}_child_ideal_pf+freq_filter]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l1d.prefetch_activate = LOAD,PREFETCH,TRANSLATION
l1d.prefetcher = child_ideal
l1d.pf_mshr_gate_pct = 95
l1d.pf_child_train_on_hit = 1
l1d.pf_child_issue_on_hit = 1
l1d.pf_child_populate_vc = 1
l1d.enable_pf_buffer = 0
ooo_cpu.enable_txvc = true
txvc.level = 1 2
txvc.sets = 32 64 128 256 65536
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
l2c.sets = 2048
l2c.ways = 8
l2c.prefetcher = no
llc.sets = 1024
llc.ways = 16
llc.prefetcher = no
