[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_txvc_size_eval
plot_type = plot_ipc
file_type = pdf

[EXPERIMENT]
name = doa_txvc_size_eval
workload = selected_qualcomm_srv_ap
debug_run = false
simulations_base = BASELINE
simulations_4KB = TXVC-4KB-FULL-ASSOC, TXVC-4KB-32WAY, TXVC-4KB-16WAY, TXVC-4KB-8WAY
simulations_8KB = TXVC-8KB-FULL-ASSOC, TXVC-8KB-32WAY, TXVC-8KB-16WAY, XVC-8KB-8WAY
#simulations = %(simulations_base)s, %(simulations_4KB)s, %(simulations_8KB)s
simulations = %(simulations_base)s, %(simulations_4KB)s

[BASELINE]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[TXVC-4KB-FULL-ASSOC]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-4KB-32WAY]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 2
txvc.ways = 32
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-4KB-16WAY]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 4
txvc.ways = 16
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-4KB-8WAY]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 8
txvc.ways = 8
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-8KB-FULL-ASSOC]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 128
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-8KB-32WAY]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 4
txvc.ways = 32
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-8KB-16WAY]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 8
txvc.ways = 16
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-8KB-8WAY]
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 16
txvc.ways = 8
txvc.data_only = true
txvc.doa_filtering = false