[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_64KB_pacipv_eval
plot_type = ipc
file_type = pdf

[EXPERIMENT]
name = txvc_replacement_eval
#workload = selected_qualcomm_srv_ap
workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_txvc_64KB = TXVC-64KB-pacipv-v${txvc.pacipv_demand_vector_idx}
simulations_txvc_128KB = TXVC-128KB-pacipv-v${txvc.pacipv_demand_vector_idx}
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc_64KB)s
#simulations = %(simulations_base)s

[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[TXVC-64KB-pacipv-v${txvc.pacipv_demand_vector_idx}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = pacipv
txvc.pacipv_demand_vector_file = ./cache/ipv/srrip_vectors.ipv
txvc.pacipv_demand_vector_idx = 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70

[TXVC-128KB-pacipv-v${txvc.pacipv_demand_vector_idx}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = pacipv
txvc.pacipv_demand_vector_file = ./cache/ipv/srrip_vectors.ipv
txvc.pacipv_demand_vector_idx = 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70
