[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_cache_eval
plot_type = plot_mpki
file_type = pdf

[EXPERIMENT]
name = txvc_cache_eval
#workload = selected_qualcomm_srv_ap
workload = google_srv
#workload = spec_cpu_2006
#workload = spec_cpu_2017
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations = BASELINE, L1D-TXVC-Inf, L2C-TXVC-Inf, LLC-TXVC-Inf

[BASELINE]
skip_simulation = false
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[L1D-TXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 1
txvc.sets = 1
txvc.ways = 32768 
txvc.cache_filtering = true
txvc.cache_filter = trace-mem
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces

[L2C-TXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 32768 
txvc.cache_filtering = true
txvc.cache_filter = trace-mem
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces

[LLC-TXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 3
txvc.sets = 1
txvc.ways = 32768 
txvc.cache_filtering = true
txvc.cache_filter = trace-mem
txvc.filter_mem_trace_path = ./data/txvc_llc_traces
