[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_txvc_base_eval
plot_type = plot_ipc
file_type = pdf

[EXPERIMENT]
name = txvc_base_eval
workload = selected_qualcomm_srv_ap
#workload = smt_qualcomm_srv_ap
simulations_base=BASELINE, iTP, xPTP, iTP+xPTP, TXVC-INF, TXVC-INF+iTP, TXVC-INF+xPTP, TXVC-INF+iTP+xPTP
simulations_4KB = TXVC-4KB, TXVC-4KB+iTP, TXVC-4KB+xPTP, TXVC-4KB+iTP+xPTP
simulations_8KB = TXVC-8KB, TXVC-8KB+iTP, TXVC-8KB+xPTP, TXVC-8KB+iTP+xPTP
simulations_32KB = TXVC-32KB, TXVC-32KB+iTP, TXVC-32KB+xPTP, TXVC-32KB+iTP+xPTP
simulations = %(simulations_base)s, %(simulations_4KB)s, %(simulations_32KB)selected_qualcomm_srv_ap

[BASELINE]
# TODO: add functionality to reuse data from other folders, setting this should not allow running this sim
skip_simulation = false
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[iTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16

[xPTP]
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[TXCV-INF]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXCV-INF+iTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXCV-INF+xPTP]
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXCV-INF+iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXCV-4KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 8
txvc.ways = 8

[TXCV-4KB+iTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 8
txvc.ways = 8

[TXCV-4KB+xPTP]
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 8
txvc.ways = 8

[TXCV-4KB+iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 8
txvc.ways = 8


