[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_cache_eval
plot_type = plot_ipc
file_type = pdf

[EXPERIMENT]
name = txvc_cache_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_Inf_base = TXVC-Inf
simulations_Inf_freq = TXVC-${txvc.level}-Inf
simulations = BASELINE, %(simulations_Inf_freq)s

[BASELINE]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[TXVC-L${txvc.level}-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 32768 
txvc.cache_filtering = false
txvc.cache_filter = oracle-mfu
#txvc.cache_filter = trace-mem
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
