[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_freq_filter_analysis
plot_type = plot_txvc_bypass
file_type = pdf
#alternative_tags = BASELINE, iTP, xPTP, iTP+xPTP, 4KB, 8KB, 16KB, 32KB, 64KB, 128KB, 256KB, 2MB
#alternative_tags = BASELINE, 4KB, 8KB, 16KB, 32KB, 64KB, 128KB, 256KB, 2MB
#64 128 256 512 1024 2048 4096 32768
#alternative_tags = BASELINE, >1, >5, >40, >100
#alternative_tags = BASELINE, 128, 512, 1024, 2048, 4096, 8192
#alternative_tags = BASELINE, 3, 5, 7, 9, 11
#alternative_tags = BASELINE, SimpleFreqFilter, BloomFreqFilter
#alternative_tags = BASELINE, TXVC:64KB-BFF:HASHES:3, TXVC:64KB-BFF:HASHES:1, TXVC:128KB-BFF:HASHES:3, TXVC:128KB-BFF:HASHES:1, TXVC:Inf-BFF:HASHES:3, TXVC:Inf-BFF:HASHES:1

[EXPERIMENT]
name = access_bloom_freq_filter_analysis
#name = test
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = debug
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_rep = iTP, xPTP, iTP+xPTP
simulations_l1d_freq_filter = TXVC-SETS-1-WAYS-${txvc.ways}-L1D_FREQ-FILTER-${txvc.filter_frequency_threshold}
simulations_l2c_bloom_freq_filter = TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-${txvc.filter_frequency_threshold}
#simulations_l2c_bloom_freq_filter = TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-${txvc.filter_frequency_threshold}-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}
#simulations_l2c_bloom_freq_filter = TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-true-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}
simulations_l2c_freq_filter = TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-${txvc.filter_frequency_threshold}
simulations_itp_l2c_bloom_freq_filter = iTP+TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-${txvc.filter_frequency_threshold}-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}
simulations_itp_xptp_l2c_bloom_freq_filter = iTP+xPTP+TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-${txvc.filter_frequency_threshold}-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}
simulations = BASELINE, %(simulations_l2c_freq_filter)s
#simulations = BASELINE, %(simulations_l2c_bloom_freq_filter)s
#simulations = BASELINE, %(simulations_rep)s, %(simulations_itp_xptp_l2c_bloom_freq_filter)s
#simulations = BASELINE, %(simulations_l2c_freq_filter)s, %(simulations_l2c_bloom_freq_filter)s
#simulations = BASELINE, TXVC-SETS-1-WAYS-512-L2C_FREQ-FILTER-THLD-1-SIZE-1024-HASHES-3, TXVC-SETS-1-WAYS-512-L2C_FREQ-FILTER-THLD-1-SIZE-1024-HASHES-1, TXVC-SETS-1-WAYS-1024-L2C_FREQ-FILTER-THLD-1-SIZE-1024-HASHES-3, TXVC-SETS-1-WAYS-1024-L2C_FREQ-FILTER-THLD-1-SIZE-1024-HASHES-1, TXVC-SETS-1-WAYS-32768-L2C_FREQ-FILTER-THLD-1-SIZE-1024-HASHES-3, TXVC-SETS-1-WAYS-32768-L2C_FREQ-FILTER-THLD-1-SIZE-1024-HASHES-1
#imulations = TEST

[BASELINE]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
#simulation_stats = ./stats/txvc_cache_eval/BASELINE/google_srv_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[BASELINE2]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
#simulation_stats = ./stats/txvc_cache_eval/BASELINE/google_srv_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
l2c.sets = 2048
l2c.ways = 8

[BASELINE3]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
#simulation_stats = ./stats/txvc_cache_eval/BASELINE/google_srv_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
l2c.sets = 2048
l2c.ways = 12

[iTP]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/iTP/selected_qualcomm_srv_ap_iTP.csv
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16

[xPTP]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/xPTP/selected_qualcomm_srv_ap_xPTP.csv
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[iTP+xPTP]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/iTP+xPTP/selected_qualcomm_srv_ap_iTP+xPTP.csv
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[TXVC-SETS-1-WAYS-${txvc.ways}-L1D_FREQ-FILTER-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 1
txvc.sets = 1
#txvc.ways = 1024 2048 4096 32768
txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = simple-freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces
txvc.filter_frequency_threshold = 1 5 10 20 30 40

[TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-${txvc.filter_frequency_threshold}]
#simulation_stats = ./stats/access_freq_filter_analysis/TXVC-SETS-1-WAYS-32768-L2C_FREQ-FILTER-1/selected_qualcomm_srv_ap_TXVC-SETS-1-WAYS-32768-L2C_FREQ-FILTER-1.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 64 128 256 512 1024 2048 4096 32768
#txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
#txvc.filter_frequency_threshold = 0
txvc.filter_frequency_threshold = 0 1


[TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-${txvc.filter_frequency_threshold}-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}]
#[TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.ways = 1024 2048 4096 32768
txvc.ways = 64 128 256 512 1024 2048 4096 32768
#txvc.ways = 1024 2048 4096
#txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = bloom-freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
#txvc.filter_frequency_threshold = 1 5 10 20 30 40
#txvc.filter_frequency_threshold = 1 5 40 100
txvc.filter_frequency_threshold = 1
#txvc.filter_size = 128 512 1024 2048 4096 8192
txvc.filter_size = 1024
#txvc.filter_num_hashes = 3 5 7 9 11
txvc.filter_num_hashes = 1
#txvc.filter_num_hashes = 5

[TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-true-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}]
#[TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.ways = 1024 2048 4096 32768
#txvc.ways = 64 128 256 512 1024 2048 4096 32768
txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = bloom-freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
#txvc.filter_frequency_threshold = 1 5 10 20 30 40
#txvc.filter_frequency_threshold = 1 5 40 100
txvc.filter_frequency_threshold = 1 5 40 100
#txvc.filter_size = 128 512 1024 2048 4096 8192
txvc.filter_size = 1024
#txvc.filter_num_hashes = 3 5 7 9 11
txvc.filter_num_hashes = 3
#txvc.filter_num_hashes = 5

[iTP+TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-${txvc.filter_frequency_threshold}-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
stlb.replacement = itp
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.ways = 1024 2048 4096 32768
txvc.ways = 64 128 256 512 1024 2048 4096 32768
#txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = bloom-freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
#txvc.filter_frequency_threshold = 1 5 10 20 30 40
#txvc.filter_frequency_threshold = 1 5 40 100
txvc.filter_frequency_threshold = 1 
#txvc.filter_size = 128 512 1024 2048 4096 8192
txvc.filter_size = 1024
#txvc.filter_num_hashes = 3 5 7 9 11
txvc.filter_num_hashes = 3

[iTP+xPTP+TXVC-SETS-1-WAYS-${txvc.ways}-L2C_FREQ-FILTER-THLD-${txvc.filter_frequency_threshold}-SIZE-${txvc.filter_size}-HASHES-${txvc.filter_num_hashes}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
stlb.replacement = itp
l2c.replacement = xptp
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.ways = 1024 2048 4096 32768
txvc.ways = 64 128 256 512 1024 2048 4096 32768
#txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = bloom-freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
#txvc.filter_frequency_threshold = 1 5 10 20 30 40
#txvc.filter_frequency_threshold = 1 5 40 100
txvc.filter_frequency_threshold = 1 
#txvc.filter_size = 128 512 1024 2048 4096 8192
txvc.filter_size = 1024
#txvc.filter_num_hashes = 3 5 7 9 11
txvc.filter_num_hashes = 3

[TEST]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 1024
txvc.cache_filtering = true
txvc.cache_filter = bloom-freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 40
txvc.filter_size = 1024
txvc.filter_num_hasahes = 5