[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_l2c_size_analysis
plot_type = plot_ipc
file_type = pdf
#alternative_tags = BASELINE, iTP, xPTP, iTP+xPTP, 4KB, 8KB, 16KB, 32KB, 64KB, 128KB, 256KB, 2MB
#alternative_tags = BASELINE, 4KB, 8KB, 16KB, 32KB, 64KB, 128KB, 256KB, 2MB
#64 128 256 512 1024 2048 4096 32768
#alternative_tags = BASELINE, >1, >5, >40, >100
#alternative_tags = BASELINE, 128, 512, 1024, 2048, 4096, 8192
#alternative_tags = BASELINE, 3, 5, 7, 9, 11
#alternative_tags = BASELINE, SimpleFreqFilter, BloomFreqFilter
#alternative_tags = BASELINE, TXVC:64KB-BFF:HASHES:3, TXVC:64KB-BFF:HASHES:1, TXVC:128KB-BFF:HASHES:3, TXVC:128KB-BFF:HASHES:1, TXVC:Inf-BFF:HASHES:3, TXVC:Inf-BFF:HASHES:1

[EXPERIMENT]
name = txvc_l2c_size_analysis
#name = test
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = debug
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_rep = iTP, xPTP, iTP+xPTP
simulations_l2c_size = L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}-TXVC-SETS-1-WAYS-${txvc.ways}
simulations = BASELINE, %(simulations_rep)s, %(simulations_l2c_size)s
#simulations = %(simulations_rep)s

[BASELINE]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
#simulation_stats = ./stats/txvc_cache_eval/BASELINE/google_srv_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16

[iTP]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/iTP/selected_qualcomm_srv_ap_iTP.csv
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16

[xPTP]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/xPTP/selected_qualcomm_srv_ap_xPTP.csv
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.sets = 2048
l2c.ways = 8
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}-TXVC-SETS-1-WAYS-${txvc.ways}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 64 128 256 512 1024 2048 4096 32768
