[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 04:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_txvc_base_eval
plot_type = plot_ipc
file_type = pdf

[EXPERIMENT]
name = txvc_base_eval
workload = selected_qualcomm_srv_ap
#workload = smt_qualcomm_srv_ap
debug_run = false
simulations_base = BASELINE, iTP, xPTP, iTP+xPTP
simulations_txvc = TXVC-INF, TXVC-INF+iTP, TXVC-INF+xPTP, TXVC-INF+iTP+xPTP
simulations_dtxvc = dTXVC-Inf, dTXVC-Inf+iTP, dTXVC-Inf+xPTP, dTXVC-Inf+iTP+xPTP
simulations = %(simulations_base)s, %(simulations_txvc)s, %(simulations_dtxvc)s
#simulations = iTP, iTP+xPTP, <%(simulations_txvc)s, %(simulations_dtxvc)s
#simulations = %(simulations_dtxvc)s

[BASELINE]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[iTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16

[xPTP]
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[TXVC-INF]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXVC-INF+iTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXVC-INF+xPTP]
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[TXVC-INF+iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8

[dTXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.data_only = true

[dTXVC-Inf+iTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.data_only = true

[dTXVC-Inf+xPTP]
ooo_cpu.instruction_prefetcher = fdip
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.data_only = true

[dTXVC-Inf+iTP+xPTP]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.data_only = true



