[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_lrfu_decay_param_eval
plot_type = ipc, mpki
file_type = pdf

[EXPERIMENT]
name = txvc_replacement_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_txvc_64KB = TXVC-64KB-lrfu-decay-${txvc.replacement_decay}
simulations_txvc_128KB = TXVC-128KB-lrfu-decay-${txvc.replacement_decay}

# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc_64KB)s, %(simulations_txvc_128KB)s
#simulations = TXVC-128KB-${txvc.replacement}

[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[TXVC-64KB-lrfu-decay-${txvc.replacement_decay}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lrfu
txvc.replacement_decay= 0.1 0.3 0.5 0.7 0.9


[TXVC-128KB-lrfu-decay-${txvc.replacement_decay}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lrfu
txvc.replacement_decay = 0.1 0.3 0.5 0.7 0.9
