[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 03:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = fig_mfu_filter_eval
plot_type = plot_ipc
file_type = pdf

[EXPERIMENT]
name = mfu_eval_no_adjust
workload = selected_qualcomm_srv_ap
debug_run = false
parallel_run = false
simulations_base = BASELINE
#simulations_4KB_base = TXVC-4KB, TXVC-4KB_MFU
#simulation_32KB_base = TXVC-32KB, TXVC-32KB_MFU
simulations_4KB_cleanup = TXVC-4KB_MFU-CLEANUP-1K, TXVC-4KB_MFU-CLEANUP-10K, TXVC-4KB_MFU-CLEANUP-100K, TXVC-4KB_MFU-CLEANUP-1M
simulations_32KB_cleanup = TXVC-32KB_MFU-CLEANUP-1K, TXVC-32KB_MFU-CLEANUP-10K, TXVC-32KB_MFU-CLEANUP-100K, TXVC-32KB_MFU-CLEANUP-1M
simulations_4KB_factor = TXVC-4KB_MFU-FACTOR-1.5, TXVC-4KB_MFU-FACTOR-2, TXVC-4KB_MFU-FACTOR-3
simulations_32KB_factor = TXVC-32KB_MFU-FACTOR-1.5, TXVC-32KB_MFU-FACTOR-2, TXVC-32KB_MFU-FACTOR-3
simulations_4KB_base = TXVC-4KB
simulations_32KB_base = TXVC-32KB
simulations_4KB_oracle = TXVC-4KB_MFU-FREQ-500, TXVC-4KB_MFU-FREQ-400, TXVC-4KB_MFU-FREQ-300, TXVC-4KB_MFU-FREQ-200, TXVC-4KB_MFU-FREQ-100
simulations_32KB_oracle = TXVC-32KB_MFU-FREQ-500, TXVC-32KB_MFU-FREQ-400, TXVC-32KB_MFU-FREQ-300, TXVC-32KB_MFU-FREQ-200, TXVC-32KB_MFU-FREQ-100
simulations_Inf_base = TXVC-Inf
simulations_Inf_oracle = TXVC-Inf_MFU-FREQ-${txvc.filter_frequency_threshold}
#simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_factor)s, $(simulations_32KB_base)s %(simulations_32KB_factor)s
#simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_oracle)s, %(simulations_32KB_base)s, %(simulations_32KB_oracle)s
#simulations = %(simulations_base)s, %(simulations_32KB_base)s, %(simulations_32KB_oracle)s
#simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_oracle)s, %(simulations_32KB_base)s, %(simulations_32KB_oracle)s
simulations = %(simulations_base)s, %(simulations_Inf_base)s, %(simulations_Inf_oracle)s

[BASELINE]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[TXVC-4KB]
skip_simulation = true
simulation_stats = ./stats/doa_cntr_size_analysis_inf-predtable_nobias/TXVC-4KB/selected_qualcomm_srv_ap_TXVC-4KB.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = false

[TXVC-4KB_MFU]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 99999999999999

[TXVC-4KB_MFU-CLEANUP-1K]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 1000

[TXVC-4KB_MFU-CLEANUP-10K]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 10000

[TXVC-4KB_MFU-CLEANUP-100K]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 100000

[TXVC-4KB_MFU-CLEANUP-1M]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 1000000

[TXVC-4KB_MFU-FACTOR-1.5]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 1.5

[TXVC-4KB_MFU-FACTOR-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 2.0

[TXVC-4KB_MFU-FACTOR-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 3.0


[TXVC-4KB_MFU-FREQ-500]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 500

[TXVC-4KB_MFU-FREQ-400]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 400

[TXVC-4KB_MFU-FREQ-300]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 300

[TXVC-4KB_MFU-FREQ-200]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 200

[TXVC-4KB_MFU-FREQ-100]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 100

[TXVC-4KB_MFU-ORACLE]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data

[TXVC-32KB]
#skip_simulation = true
#simulation_stats = ./stats/doa_cntr_size_analysis_inf-predtable_nobias/TXVC-32KB/selected_qualcomm_srv_ap_TXVC-32KB.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.data_only = true
txvc.cache_filtering = false

[TXVC-32KB_MFU]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 99999999999999

[TXVC-32KB_MFU-CLEANUP-1K]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000

[TXVC-32KB_MFU-CLEANUP-10K]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 10000

[TXVC-32KB_MFU-CLEANUP-100K]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 100000

[TXVC-32KB_MFU-CLEANUP-1M]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000

[TXVC-32KB_MFU-FACTOR-1.5]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 1.5

[TXVC-32KB_MFU-FACTOR-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 2.0

[TXVC-32KB_MFU-FACTOR-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 3.0

[TXVC-32KB_MFU-ORACLE]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 512
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data



[TXVC-32KB_MFU-FREQ-500]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 500

[TXVC-32KB_MFU-FREQ-400]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 400

[TXVC-32KB_MFU-FREQ-300]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 300

[TXVC-32KB_MFU-FREQ-200]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 200

[TXVC-32KB_MFU-FREQ-100]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 100

[TXVC-32KB_MFU-FREQ-1]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_cleanup_interval = 1000000
txvc.filter_top_n_factor = 10000.0
txvc.filter_frequency_threshold = 1

[TXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.data_only = true
txvc.cache_filtering = false

[TXVC-Inf_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.data_only = true
txvc.filter_frequency_threshold = 1 2 100 200 300 400 500