[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_64KB_vs_l2c_2048KB_budget_analysis2
plot_type = plot_ipc
#plot_type = plot_mpki
file_type = pdf
#alternative_tags = BASELINE, TXVC, TXVC-FreqFilter

[EXPERIMENT]
name = txvc_budget_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = debug
debug_run = false
parallel_run = true
# 64KB TXVC vs 2048KB L2C
simulations_base_l2c_1.25MB = BASELINE-L2C-1.2MB
simulations_txvc_l2c_1.25MB = L2C-1.25MB-TXVC-16KB-FILTER-${txvc.cache_filter}, L2C-1.25MB-TXVC-32KB-FILTER-${txvc.cache_filter}, L2C-1.25MB-TXVC-64KB-FILTER-${txvc.cache_filter}
simulations_base_l2c_1.5MB = BASELINE-L2C-1.5MB
simulations_txvc_l2c_1.5MB = L2C-1.5MB-TXVC-16KB-FILTER-${txvc.cache_filter}, L2C-1.5MB-TXVC-32KB-FILTER-${txvc.cache_filter}, L2C-1.5MB-TXVC-64KB-FILTER-${txvc.cache_filter}
simulations_base_l2c_2MB = BASELINE-L2C-2MB
simulations_txvc_l2c_2MB = L2C-2MB-TXVC-16KB-FILTER-${txvc.cache_filter}, L2C-2MB-TXVC-32KB-FILTER-${txvc.cache_filter}, L2C-2MB-TXVC-64KB-FILTER-${txvc.cache_filter}


# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base_l2c_1.25MB)s, %(simulations_txvc_l2c_1.25MB)s
#simulations = %(simulations_base_l2c_1.5MB)s, %(simulations_txvc_l2c_1.5MB)s
#simulations = %(simulations_base_l2c_2MB)s, %(simulations_txvc_l2c_2MB)s

# L2C 1.25MB TXVC 16KB, 32KB, 64KB
[BASELINE-L2C-1.25MB]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2560
l2c.ways = 8
llc.sets = 2048
llc.ways = 16
