[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = bestof_txvc_256KB_lfu_summary_analysis
#plot_type = plot_ipc
plot_type = plot_mpki
#plot_type = plot_txvc_bypass
file_type = pdf
#alternative_tags = BASELINE, iTP, xPTP, iTP+xPTP, TXVC-32KB, TXVC-64KB, TXVC-128KB, TXVC-256KB
#alternative_tags = BASELINE, iTP, xPTP, iTP+xPTP, TXVC, TXVC-SimpleFilter, TXVC-FreqFilter, TXVC-BloomFilter, TXVC-OracleMFU, TXVC-BeladyOPT
alternative_tags = BASELINE, iTP, xPTP, iTP+xPTP, TXVC, TXVC-FreqFilter, iTP+xPTP+TXVC, iTP+xPTP+TXVC-FreqFilter
#alternative_tags = TXVC, TXVC-SimpleFilter, TXVC-FreqFilter, TXVC-BloomFilter, OracleMFU, TXVC-BeladyOPT

[EXPERIMENT]
#name = txvc_summary_analysis
name = txvc_l2c_1MB_summary_analysis
#name = txvc_8ways_summary_analysis
#name = test
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = debug
debug_run = false
parallel_run = true
simulations_base = BASELINE-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}
simulations_rep = iTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}, xPTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}, iTP+xPTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}
simulations_txvc = L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}-TXVC-SETS-1-WAYS-${txvc.ways}-FILTER-${txvc.cache_filter}-REP-${txvc.replacement}
simulations_itp+xptp+txvc = iTP+xPTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}-TXVC-SETS-1-WAYS-${txvc.ways}-FILTER-${txvc.cache_filter}-REP-${txvc.replacement}
simulations = %(simulations_base)s, %(simulations_rep)s, %(simulations_txvc)s, %(simulations_itp+xptp+txvc)s
#simulations = %(simulations_itp+xptp+txvc)s
#simulations = %(simulations_base)s, %(simulations_rep)s
#simulations = TEST

[BASELINE-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
#simulation_stats = ./stats/txvc_cache_eval/BASELINE/google_srv_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
#l2c.sets = 1024 
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16

[iTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/iTP/selected_qualcomm_srv_ap_iTP.csv
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
#l2c.sets = 1024 
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16

[xPTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}]
#skip_simulation = true
#simulation_stats = ./stats/txvc_base_eval/xPTP/selected_qualcomm_srv_ap_xPTP.csv
ooo_cpu.instruction_prefetcher = fdip
#l2c.sets = 1024 
l2c.sets = 2048
l2c.ways = 8
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16

[iTP+xPTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}]
ooo_cpu.instruction_prefetcher = fdip
stlb.replacement = itp
#l2c.sets = 1024 
l2c.sets = 2048
l2c.ways = 8
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16


[L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}-TXVC-SETS-1-WAYS-${txvc.ways}-FILTER-${txvc.cache_filter}-REP-${txvc.replacement}]
ooo_cpu.instruction_prefetcher = fdip
#l2c.sets = 1024
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.sets = 8
#txvc.ways = 512 
#txvc.ways = 1024 
#txvc.ways = 2048 
txvc.ways = 4096
#txvc.ways = 512 1024 2048 4096
txvc.cache_filtering = true
#txvc.cache_filter = none simple-freq-filter freq-filter bloom-freq-filter oracle-mfu beladyOPT-set
txvc.cache_filter = none freq-filter
#txvc.cache_filter = beladyOPT-set
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.filter_size = 1024
txvc.filter_num_hashes = 3
#txvc.replacement = lru
txvc.replacement = lfu


[iTP+xPTP-L2C-SETS-${l2c.sets}-WAYS-${l2c.ways}-TXVC-SETS-1-WAYS-${txvc.ways}-FILTER-${txvc.cache_filter}-REP-${txvc.replacement}]
ooo_cpu.instruction_prefetcher = fdip
l1d.replacement = itp
#l2c.sets = 1024
l2c.sets = 2048
l2c.ways = 8
l2c.replacement = xptp
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
#txvc.sets = 8
#xvc.ways = 512 
#txvc.ways = 1024 
#txvc.ways = 2048 
txvc.ways = 4096
#txvc.ways = 512 1024 2048 4096
txvc.cache_filtering = true
#txvc.cache_filter = none simple-freq-filter freq-filter bloom-freq-filter oracle-mfu beladyOPT-set
txvc.cache_filter = none freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.filter_size = 1024
txvc.filter_num_hashes = 3
#txvc.replacement = lru
txvc.replacement = lfu