[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
#plot_name = txvc_lfu_decay_param_eval
plot_name = txvc_pacipv_comparison
plot_type = ipc, mpki
file_type = pdf
group_size = 4
#alternative_tags = BASELINE, LRU, LFU, LFU++, LFU-Halving, LFU-Leaf-PTE, LRFU, LRFU-WSS, LFU-PC

[EXPERIMENT]
name = txvc_replacement_eval
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
#simulations_txvc_64KB = TXVC-64KB-${txvc.replacement}, TXVC-64KB-${txvc.replacement}-halve-period-${txvc.halve_period}, TXVC-64KB-${txvc.replacement}-lvl-${txvc.replacement_pte_threshold}, TXVC-64KB-${txvc.replacement}-decay-${txvc.replacement_decay}, TXVC-64KB-lrfu_wss-thrld-${txvc.replacement_threshold}-ws-${txvc.replacement_window_size}, TXVC-64KB-lfu_pchot-reset-${txvc.replacement_pc_reset_interval}, TXVC-64KB-srrip, TXVC-64KB-pacipv-v${txvc.pacipv_demand_vector_idx}
#simulations_txvc_128KB = TXVC-128KB-${txvc.replacement}, TXVC-128KB-${txvc.replacement}-halve-period-${txvc.halve_period}, TXVC-128KB-${txvc.replacement}-lvl-${txvc.replacement_pte_threshold}, TXVC-128KB-${txvc.replacement}-decay-${txvc.replacement_decay}, TXVC-128KB-lrfu_wss-thrld-${txvc.replacement_threshold}-ws-${txvc.replacement_window_size}, TXVC-128KB-lfu_pchot-reset-${txvc.replacement_pc_reset_interval}, TXVC-128KB-srrip, TXVC-128KB-pacipv-v${txvc.pacipv_demand_vector_idx}
simulations_txvc_64KB = TXVC-64KB-${txvc.replacement}, TXVC-64KB-pacipv-v${txvc.pacipv_demand_vector_idx}
simulations_txvc_128KB = TXVC-128KB-${txvc.replacement}, TXVC-128KB-pacipv-v${txvc.pacipv_demand_vector_idx}
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc_64KB)s, %(simulations_txvc_128KB)s
#simulations = TXVC-64KB-pacipv-v${txvc.pacipv_demand_vector_idx}, TXVC-128KB-pacipv-v${txvc.pacipv_demand_vector_idx}
#simulations = %(simulations_base)s, %(simulations_txvc_128KB)s
#simulations = TXVC-64KB-${txvc.replacement}, TXVC-128KB-${txvc.replacement}

[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[TXVC-64KB-${txvc.replacement}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lru lfu srrip

[TXVC-64KB-${txvc.replacement}-halve-period-${txvc.halve_period}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu_halving
txvc.halve_period = 1000000


[TXVC-64KB-${txvc.replacement}-lvl-${txvc.replacement_pte_threshold}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu_leaf
txvc.replacement_evict_leaf_nodes = false
txvc.replacement_pte_threshold = 2

[TXVC-64KB-${txvc.replacement}-decay-${txvc.replacement_decay}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lrfu
txvc.replacement_decay= 0.9

[TXVC-64KB-lrfu_wss-thrld-${txvc.replacement_threshold}-ws-${txvc.replacement_window_size}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filterq
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lrfu_wss
txvc.replacement_threshold = 0.1
txvc.replacement_window_size = 1000

[TXVC-64KB-lfu_pchot-reset-${txvc.replacement_pc_reset_interval}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu_pchot
txvc.replacement_pc_reset_interval = 100000000

[TXVC-64KB-srrip]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = srrip

[TXVC-64KB-pacipv-v${txvc.pacipv_demand_vector_idx}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = pacipv
txvc.pacipv_demand_vector_file = ./cache/ipv/srrip_vectors.ipv
txvc.pacipv_demand_vector_idx = 26

[TXVC-128KB-${txvc.replacement}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lru lfu srrip


[TXVC-128KB-${txvc.replacement}-halve-period-${txvc.halve_period}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu_halving
txvc.halve_period = 1000000

[TXVC-128KB-${txvc.replacement}-lvl-${txvc.replacement_pte_threshold}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu_leaf
txvc.replacement_evict_leaf_nodes = false
txvc.replacement_pte_threshold = 2

[TXVC-128KB-${txvc.replacement}-decay-${txvc.replacement_decay}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lrfu
txvc.replacement_decay= 0.9

[TXVC-128KB-lrfu_wss-thrld-${txvc.replacement_threshold}-ws-${txvc.replacement_window_size}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filterq
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lrfu_wss
txvc.replacement_threshold = 0.1
txvc.replacement_window_size = 1000

[TXVC-128KB-lfu_pchot-reset-${txvc.replacement_pc_reset_interval}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu_pchot
txvc.replacement_pc_reset_interval = 100000000

[TXVC-128KB-srrip]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = srrip

[TXVC-128KB-pacipv-v${txvc.pacipv_demand_vector_idx}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = pacipv
txvc.pacipv_demand_vector_file = ./cache/ipv/srrip_vectors.ipv
txvc.pacipv_demand_vector_idx = 26
