[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_instr_vs_data_pte_eval
plot_type = ipc, mpki, mpki_breakdown
file_type = pdf

[EXPERIMENT]
name = txvc_instr_vs_data_pte_eval
#name = test
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_txvc = TXVC-64KB, iTXVC-64KB, dTXVC-64KB, TXVC-128KB, iTXVC-128KB, dTXVC-128KB

# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc)s
#simulations = TXVC-128KB-${txvc.replacement}

[BASELINE]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[TXVC-64KB]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu 


[iTXVC-64KB]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
#txvc.cache_filtering = true
#txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu 
txvc.instr_only = true
txvc.data_only = false

[dTXVC-64KB]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64
txvc.ways = 16
#txvc.cache_filtering = true
#txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu 
txvc.instr_only = false
txvc.data_only = true

[TXVC-128KB]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
#txvc.cache_filtering = true
#txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu

[iTXVC-128KB]
#skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
#txvc.cache_filtering = true
#txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
txvc.instr_only = true
txvc.data_only = false

[dTXVC-128KB]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
#txvc.cache_filtering = true
#txvc.cache_filter = freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu
txvc.instr_only = false
txvc.data_only = true