[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 01:00:00
batch_size = 10

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
#plot_name = fig_doa_cntr_size_analysis-inf-predtable_nobias
plot_name = fig_doa_cntr_size_analysis-inf-predtable
plot_type = plot_mpki
file_type = pdf

[EXPERIMENT]
#name = doa_cntr_size_analysis_inf-predtable_nobias
name = doa_cntr_size_analysis_inf-predtable
#name = doa2_cntr_size_analysis_inf-predtable_nobias
workload = selected_qualcomm_srv_ap
#workload = smt_qualcomm_srv_ap
#workload = debug
debug_run = false
parallel_run = true
#simulations=BASELINE, TXVC-4KB_DOA-CNTR_SZ-2, TXVC-4KB_DOA-CNTR_SZ-3, TXVC-4KB_DOA-CNTR_SZ-4, TXVC-8KB_DOA-CNTR_SZ-2, TXVC-8KB_DOA-CNTR_SZ-3, TXVC-8KB_DOA-CNTR_SZ-4, TXVC-32KB_DOA-CNTR_SZ-2, TXVC-32KB_DOA-CNTR_SZ-3, TXVC-32KB_DOA-CNTR_SZ-4
simulations_base = BASELINE
simulations_4KB_base = TXVC-4KB
simulations_32KB_base = TXVC-32KB
simulations_4KB_doa = TXVC-4KB_DOA-NAIVE, TXVC-4KB_DOA-CNTR_SZ-1, TXVC-4KB_DOA-CNTR_SZ-2, TXVC-4KB_DOA-CNTR_SZ-3, TXVC-4KB_DOA-CNTR_SZ-4
simulations_32KB_doa = TXVC-32KB_DOA-NAIVE, TXVC-32KB_DOA-CNTR_SZ-1, TXVC-32KB_DOA-CNTR_SZ-2, TXVC-32KB_DOA-CNTR_SZ-3, TXVC-32KB_DOA-CNTR_SZ-4
#simulations = %(simulations_base)s, %(simulations_4KB)s, %(simulations_32KB)s
simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_doa)s, %(simulations_32KB_base)s, %(simulations_32KB_doa)s

[BASELINE]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[TXCV-INF]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_dTXVC-Inf.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-4KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = false

[TXVC-4KB_DOA-NAIVE]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = doa-simple


[TXVC-4KB_DOA-CNTR_SZ-1]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.data_only = true
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 1
txvc.dbpred_use_bias = true

[TXVC-4KB_DOA-CNTR_SZ-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 2
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-4KB_DOA-CNTR_SZ-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 3
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-4KB_DOA-CNTR_SZ-4]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 4
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-4KB_DOA-CNTR_SZ-5]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 5
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-8KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 16
txvc.ways = 8
txvc.data_only = true
txvc.doa_filtering = false

[TXVC-8KB_DOA-CNTR_SZ-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 16
txvc.ways = 8
txvc.doa_filtering = true
txvc.dbpred_cntr_size = 4
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-8KB_DOA-CNTR_SZ-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 16
txvc.ways = 8
txvc.doa_filtering = true
txvc.dbpred_cntr_size = 8
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-8KB_DOA-CNTR_SZ-4]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 16
txvc.ways = 8
txvc.doa_filtering = true
txvc.dbpred_cntr_size = 16
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-32KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.data_only = true
txvc.cache_filtering = false

[TXVC-32KB_DOA-NAIVE]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa-simple
txvc.data_only = true

[TXVC-32KB_DOA-CNTR_SZ-1]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 1
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-32KB_DOA-CNTR_SZ-2]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 2
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-32KB_DOA-CNTR_SZ-3]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 3
txvc.data_only = true
txvc.dbpred_use_bias = true

[TXVC-32KB_DOA-CNTR_SZ-4]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = doa
txvc.dbpred_cntr_size = 4
txvc.data_only = true
txvc.dbpred_use_bias = true


