[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 5

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = access_freq_size_analysis_l3
#plot_name = access_freq_analysis_l2
plot_type = plot_ipc
file_type = pdf
#alternative_tags = BASELINE, 2MB, 1MB, 512KB, 256KB, 128KB, 64kb, 32KB, 16KB, 8KB, 4KB

[EXPERIMENT]
name = access_freq_size_analysis_l3
#name = access_freq_analysis_l2
workload = selected_qualcomm_srv_ap
#workload = google_srv
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_4KB_base = TXVC-4KB
simulations_4KB_freq = TXVC-4KB_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_32KB_base = TXVC-32KB
simulations_32KB_freq = TXVC-32KB_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_Inf_base = TXVC-Inf
simulations_Inf_freq = TXVC-Inf_MFU-FREQ-${txvc.filter_frequency_threshold}
simulations_txvc = TXVC-4KB, TXVC-8KB, TXVC-16KB, TXVC-32KB, TXVC-64KB, TXVC-128KB, TXVC-256KB, TXVC-512KB, TXVC-1024KB, TXVC-2048KB, TXVC-4096KB, TXVC-8192KB, TXVC-16384KB, TXVC-32768KB, TXVC-65536KB
#simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_factor)s, $(simulations_32KB_base)s %(simulations_32KB_factor)s
#simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_oracle)s, %(simulations_32KB_base)s, %(simulations_32KB_oracle)s
#simulations = %(simulations_base)s, %(simulations_32KB_base)s, %(simulations_32KB_oracle)s
#simulations = %(simulations_base)s, %(simulations_4KB_base)s, %(simulations_4KB_oracle)s, %(simulations_32KB_base)s, %(simulations_32KB_oracle)s, %(simulations_Inf_base)s, %(simulations_Inf_oracle)s
#simulations = %(simulations_base)s, %(simulations_Inf_base)s, %(simulations_Inf_oracle)s
#simulations = BASELINE, TXVC-32KB, %(simulations_32KB_freq)s, %(simulations_Inf_freq)s
simulations = BASELINE, TXVC-SETS-1-WAYS-${txvc.ways}
#simulations = BASELINE, TXVC-SETS-${txvc.sets}-WAYS-8
#simulations = BASELINE, %(simulations_Inf_freq)s
#simulations = BASELINE, %(simulations_32KB_freq)s, %(simulations_4KB_freq)s

[BASELINE]
skip_simulation = true
simulation_stats = ./stats/txvc_base_eval/BASELINE/selected_qualcomm_srv_ap_BASELINE.csv
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16

[TXVC-4KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = false

[TXVC-4KB_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 1
txvc.ways = 64
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces
txvc.filter_frequency_threshold = 2 3 

[TXVC-32KB]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = false

[TXVC-32KB_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 64
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_l1d_traces
txvc.filter_frequency_threshold = 2 3

[TXVC-Inf]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 32768
txvc.cache_filtering = false

[TXVC-Inf_MFU-FREQ-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 32768
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_llc_traces
txvc.filter_frequency_threshold = 2 4 10 40 60 80 100 200 300 400 500
#txvc.filter_frequency_threshold = 40 60 80

[TXVC-Inf_MFU-FREQ2-${txvc.filter_frequency_threshold}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16 
ooo_cpu.enable_txvc = true
txvc.sets = 20480
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data
txvc.filter_frequency_threshold = 3

# 163840

[TXVC-SETS-1-WAYS-${txvc.ways}]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 3
txvc.sets = 1
txvc.ways = 64 128 256 512 1024 2048 4096 8192 16384 32768 
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data/txvc_llc_traces
txvc.filter_frequency_threshold = 2

[TXVC-SETS-${txvc.sets}-WAYS-8]
ooo_cpu.instruction_prefetcher = fdip
llc.sets = 1537
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.sets = 4 8 16 32 128 256 512 1024 2048 4096
#txvc.ways = 64 128 256 512 1024 2048 4096 8192 16384 32768 
txvc.ways = 8
txvc.cache_filtering = true
txvc.cache_filter = oracle-mfu
txvc.filter_mem_trace_path = ./data
txvc.filter_frequency_threshold = 3