[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 02:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_reduced_reuse_distance_filter_tune_median2
plot_type = ipc, mpki
file_type = pdf
#alternative_tags = BASELINE, 2, 4, 8, 16, 32, 64, 100, 500, 1000, 10000, 100000
#alternative_tags = BASELINE, 0.3, 0.4, 0.5, 0.7, 0.8, 0.9
alternative_tags = BASELINE, 512, 1024, 4096, 8192, 16384
#ylabel = "# Samples"

[EXPERIMENT]
name = txvc_reuse_distance_filter_tune
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
#workload = test
debug_run = false
parallel_run = true
simulations_base = BASELINE
simulations_txvc_64KB = TXVC_64KB_${txvc.cache_filter}-threshold-${txvc.cache_filter_reuse_distance_threshold}-lratio-${txvc.cache_filter_reuse_long_ratio}-samples-${txvc.cache_filter_reuse_min_samples}
simulations_txvc_128KB = TXVC-128KB-${txvc.cache_filter}-replacement-${txvc.replacement}
# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base)s, %(simulations_txvc_64KB)s
#, %(simulations_txvc_128KB)s


[BASELINE]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[TXVC_64KB_${txvc.cache_filter}-threshold-${txvc.cache_filter_reuse_distance_threshold}-lratio-${txvc.cache_filter_reuse_long_ratio}-samples-${txvc.cache_filter_reuse_min_samples}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 64 
txvc.ways = 16
txvc.cache_filtering = true
txvc.cache_filter = reuse-distance
txvc.cache_filter_memory_trace_path = ./data/txvc_mem_access/TXVC-64KB
txvc.cache_filter_reuse_distance_threshold = 512 1024 4096 8192 16384
#txvc.cache_filter_reuse_min_samples = 2 4 8 16 32 64 100 500 1000 10000 100000
txvc.cache_filter_reuse_min_samples = 3 8 16
txvc.cache_filter_reuse_long_ratio = 0.0
txvc.replacement = lfu 

[TXVC_128KB_${txvc.cache_filter}-threshold-${txvc.cache_filter_reuse_distance_threshold}-lratio-${txvc.cache_filter_reuse_long_ratio}-samples-${txvc.cache_filter_reuse_min_samples}]
skip_simulation = true
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 2048
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 128
txvc.ways = 16
txvc.cache_filtering = true
#txvc.cache_filter = none freq-filter
txvc.cache_filter = reuse-distance
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.cache_filter_reuse_distance_threshold = 2048
txvc.cache_filter_reuse_min_samples = 2 3 4 5 6
txvc.cache_filter_reuse_long_ratio = 0.8
txvc.replacement = lfu 