[BASE]
ROOT_DIR = .
CHAMPSIM_DIR = %(ROOT_DIR)s/ChampSim
TRACE_DIR = %(ROOT_DIR)s/traces
DUMP_DIR = %(ROOT_DIR)s/data
STATS_DIR = %(ROOT_DIR)s/stats
FIGURES_DIR = %(ROOT_DIR)s/figures 
SLIDES_DIR = %(ROOT_DIR)s/slides

[SIMULATION]
warmup_instructions = 50000000
run_instructions = 100000000
time = 04:00:00
batch_size = 20

[PARSING]
parse_raw_stats = true
parse_reuse_distance_stats = false

[PLOTTING]
plot_name = txvc_budget_eval_l2c_1.5MB
plot_type = ipc, mpki
file_type = pdf
alternative_tags = BASELINE, TXVC-16MB, TXVC-16MB-FreqFilter, TXVC-32MB, TXVC-32MB-FreqFilter, TXVC-64MB, TXVC-64MB-FreqFilter
#, TXVC-128MB, TXVC-128MB-FreqFilter


[EXPERIMENT]
name = txvc_budget_eval
#name = txvc_budget_eval_llc_1MB
workload = selected_qualcomm_srv_ap
#workload = google_srv
#workload = spec_cpu_2017
#workload = gapp
#workload = debug
debug_run = false
parallel_run = true
simulations_base_l2c_1.5MB = BASELINE-L2C-1.5MB
simulations_txvc_l2c_1.5MB = L2C-1.5MB-TXVC-16KB-FILTER-${txvc.cache_filter}, L2C-1.5MB-TXVC-32KB-FILTER-${txvc.cache_filter}, L2C-1.5MB-TXVC-64KB-FILTER-${txvc.cache_filter}
#L2C-1.5MB-TXVC-128KB-FILTER-${txvc.cache_filter}

# SIMULATIONS TO ACTUALLY RUN
simulations = %(simulations_base_l2c_1.5MB)s, %(simulations_txvc_l2c_1.5MB)s

# L2C 1.5MB TXVC 16KB, 32KB, 64KB
[BASELINE-L2C-1.5MB]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 3072
l2c.ways = 8
llc.sets = 1024
llc.ways = 16

[L2C-1.5MB-TXVC-16KB-FILTER-${txvc.cache_filter}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 3072
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 256
txvc.cache_filtering = true
txvc.cache_filter = none freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu

[L2C-1.5MB-TXVC-32KB-FILTER-${txvc.cache_filter}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 3072
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 512
txvc.cache_filtering = true
txvc.cache_filter = none freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu

[L2C-1.5MB-TXVC-64KB-FILTER-${txvc.cache_filter}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 3072
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 1024
txvc.cache_filtering = true
txvc.cache_filter = none freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu

[L2C-1.5MB-TXVC-128KB-FILTER-${txvc.cache_filter}]
ooo_cpu.instruction_prefetcher = fdip
l2c.sets = 3072
l2c.ways = 8
llc.sets = 1024
llc.ways = 16
ooo_cpu.enable_txvc = true
txvc.level = 2
txvc.sets = 1
txvc.ways = 2048
txvc.cache_filtering = true
txvc.cache_filter = none freq-filter
txvc.filter_mem_trace_path = ./data/txvc_l2c_traces
txvc.filter_frequency_threshold = 2
txvc.replacement = lfu